### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by asmeurer** [gnab/remark#104]
I gave a presentation yesterday using Remark. It was mostly successful, but there was one thing that was a little disastrous. The font was _way_ too small for people to see on the screen. Increasing the font size does nothing. I finally figured out that I can force the font to be bigger using the accessibility settings in the browser (Safari in this case).

I suggest:
- Allow Cmd-+ or whatever to actually make the font bigger. This is something that pretty much every presenter has to do, because the font is always smaller than they think it should be.
- Make the default font size in the default theme way bigger. 

Aside from these issues, Remark worked very well for me (well this and the indentation thing, but no one noticed that but me). It was super easy to write the slides, a big difference from what I've done in the past (beamer). [This](https://github.com/asmeurer/python3-presentation) is the presentation if you are intereseted.

**Comment by William-Yeh** [comment]
I'm made a primary zoom in/out for remark:

  - Source: https://github.com/William-Yeh/remark-zoom
  - Online demo: http://william-yeh.github.io/remark-zoom/

I've only tested my **remark-zoom** on a limited of browsers (Chrome, Firefox, Safari on Mac OS X "Yosemite"). Feel free to comment on this.  Thanks!

**Comment by tripu** [comment]
@William-Yeh Thanks for that tool. I also noticed that it's not possible to scale contents normally using the browser zoom features. That is an accessibility issue.

Any chance that @William-Yeh's zoom feature goes upstream, @gnab? (Or is it possible to adjust font size already, and maybe I haven't noticed?)

**Comment by William-Yeh** [comment]
Re @tripu :

I'm not good at CSS, and my remark-zoom still doesn't handle the zooming correctly in all cases.

**Comment by Tamriel** [comment]
I still would love to see the ability to change the font size :-)

**Comment by alexandrnikitin** [comment]
I second @Tamriel , ability to change the font size is important.

**Comment by Vebryn** [comment]
+1

**Comment by reactormonk** [comment]
In case anyone comes across this, you can change the font size statically via

```
      .remark-slide-content { font-size: 40px; }
```

**Comment by freder** [comment]
I just ran into the same problem.

if you ask me, `cmd`-`+`/`-` to work as expected is crucial! having to edit css during a presentation isn't really an acceptable solution.

isn't there a way to simply turn of _automatic scaling_ for those who don't need it?

**Comment by freder** [comment]
what I came up with:

```html
<style>
	:root {
		--font-size: 22px;
	}
	.remark-slide-content {
		font-size: var(--font-size);
	}
</style>
<script>
	const root = document.documentElement;
	const step = 2;
	window.addEventListener('keydown', (event) => {
		const fs = getComputedStyle(root).getPropertyValue('--font-size');
		let val = parseFloat(fs);
		if (event.metaKey && event.key === '-') {
			val -= step;
			root.style.setProperty('--font-size', `${val}px`);
		} else if (event.metaKey && event.key === '=') {
			val += step;
			root.style.setProperty('--font-size', `${val}px`);
		}
	});
</script>
```
