### ISSUE TITLE
Ability to highlight selected line(s) in source code

### ISSUE THREAD

**Issue by szpak** [gnab/remark#115]
It would be useful to provide a way to highlight selected line(s) in source code to pay audience attention on specific aspect(s).

**Comment by skyronic** [comment]
Has this feature been disabled now? The demos are not working. How do I bring it back?

**Comment by skyronic** [comment]
Ok after digging through the code a bit I found that this has to be enabled manually using

```
      var slideshow = remark.create({
        highlightLines: true
      });
```

then it works. Leaving it here for anyone else who gets stuck. Thanks!
