### ISSUE TITLE
Style in Code Block

### ISSUE THREAD

**Issue by StephenHesperus** [gnab/remark#116]
Hello, I wanna do this with remark.js:
When inside code block:

```
function say_hello_to(you) {
    // __I_wanna_be_strong__
    // _I_wanna_emphasize_this_
    // .custom-class[yummy...]
    alert("Hello, " + you + "!");
}
```

The tokens `__strong__`, `_em_` and `.class-name[blah...]` should work just as they do outside the block, meaning they are interpreted as **strong**, _em_ and `<div class="class-name">blah...</div>`, instead of showing the raw markdown.
Is this **possible**?
Maybe process those tokens first then wrap them into a `<pre><code></code></pre>` block?

I really **love** _remark.js_!

**Comment by rauschma** [comment]
This is what I am looking for! However, in order to not clash with programming language syntaxes (such as JavaScript’s, which uses backticks quite a lot these days), I’d want to use non-ASCII characters to delimit, e.g. « and »

Example:

```js
function foo() {
    «return» 123;
}
```

**Comment by rauschma** [comment]
After the merging of the following pull request, you can now customize the delimiters of the `highlightSpans` configuration option: https://github.com/gnab/remark/pull/436

**Comment by utdrmac** [comment]
Submit a pull request with documentation on how to use this new feature with examples!!

**Comment by rauschma** [comment]
Good point! I just added documentation to the wiki page: https://github.com/gnab/remark/wiki/Configuration#highlighting
