### ISSUE TITLE
"Fullscreen" Background

### ISSUE THREAD

**Issue by ysndr** [gnab/remark#121]
Hey

I am currently frustrating creating a slideshow which schould include a background over the whole slide...
Sadly that seems not possible as I tried it alot - so I have to ask the creator :)
How can I create a slide with a fullscreen background **If** i can?

**Comment by kepeket** [comment]
Hello

sorry to re-open that issue, but 
<pre>
background-position: center;
background-repeat: no-repeat;
background-size: contain;      /* applied using JavaScript only if background-image is larger than slide */
</pre>

does not seem to work.

My picture is 4500px wide and 3300px high, my slide is 1920x1280px, and changing these three make nothing.

Am i doing it wrong ?

```mardown
# that is the top of the file markdown.md
class: center, middle
background-size: 30%;
background-position: left;
background-image: url(/img/bg-health.jpg)
count: false

# Big title
## Subtitle

---

# Next slide title
```

**Comment by dergraaf** [comment]
Same problem here. Adding `.remark-slide-content {
    background-size: contain;
}` to the CSS style solved the problem for me.

**Comment by ShaneCurcuru** [comment]
Updating the remark.min.js library to the 0.14 version fixed this issue for me such that this slide fills with the image as expected:

background-image: url(background.jpg)
background-size: cover;
