### ISSUE TITLE
Randomly treating `---` as a horizontal rule?

### ISSUE THREAD

**Issue by drlabratory** [gnab/remark#122]
I'm putting a slide show together, and after the fourth slide, it is treating all `---` as horizontal rules instead of new slides. I can't for the life of me see why. Example is here:

https://github.com/drlabratory/shell-slides/blob/gh-pages/index.html

and the rendered page is here:

http://drlabratory.github.io/shell-slides/

This is on the dev version, but also happens fetching it from remark-latest.min.js

**Comment by jeffkile** [comment]
Just ran into this as well, glad I found this issue or I would have been stumped. Might make sense to have remark.js just ignore the trailing spaces and page break anyway

**Comment by bskaggs** [comment]
Same problem, same cause.  Thanks!
