### ISSUE TITLE
Escaping Content Classes

### ISSUE THREAD

**Issue by betehess** [gnab/remark#123]
The problem is that the syntax for "content classes" clashed with common Scala syntax, eg. scala.Option[A].

**Comment by gnab** [comment]
I fixed this (finally) in version 0.10.2.

`scala.class[.]Option[Int]` as normal content needs to be `scala\.class[.]Option[Int]` with the `\.class` to prevent expansion.

Inside inline code, the expansion is disabled:

    `scala.class[.]Option[Int]`

So no escaping is needed anymore.
