### ISSUE TITLE
MathJax second pair of brackets as subscript

### ISSUE THREAD

**Issue by mrquincle** [gnab/remark#127]
Using two times brackets for a subscript fails:

```
$w_{in}=1.0$, and ... $w_{out}=0.1$:
```

It is also the case within the same line:

```
$$x_{out} = f(x_{in})$$
```

In both case suddenly the math doesn't get rendered anymore. If I replace `x_{out}` with `x_o` and `x_{in}` with `x_i` it works, but this is not an option for most of my formulas.

Probably there is some conflict going on with remark?

**Comment by RoyiAvital** [comment]
@gnab , MathJax has the option to look for any class defined. Could a pre processor take care of it?
