### ISSUE TITLE
Content classes not rendered correct when using content expression on template

### ISSUE THREAD

**Issue by riezebosch** [gnab/remark#137]
When using the {{content}} expression on a template slide, the content of content classes have strange output: ,[object Object],. See: http://codepen.io/riezebosch/pen/nceGm for an example.

**Comment by kynan** [comment]
This is still an issue in 0.10.2. Unfortunately this makes template slides effectively unusable.

**Comment by gnab** [comment]
This issue has been stuck in the queue for a while. I'll hopefully have time to work at it shortly.

**Comment by kynan** [comment]
I had a look through the code trying to understand what's going on but couldn't figure out where to start. Thanks for tackling the issue!
