### ISSUE TITLE
Multiple Slideshows

### ISSUE THREAD

**Issue by eljefe6a** [gnab/remark#150]
The release notes for 0.5 say you can multiple slideshows. I looked and can't find an example of how to do this. Could you provide an example?

**Comment by aldarionsevero** [comment]
Tried the ![:include](1.md) on the single version of remark, and it did not work. How can I properly use it?

**Comment by gnab** [comment]
@aldarionsevero remark currently doesn't come with any macros, but you can define your own `include` macro using the code supplied by @eljefe6a:

```
remark.macros.include = function () {
  var url = this;
  var xmlhttp = new XMLHttpRequest();
  xmlhttp.open('GET', this, false);
  xmlhttp.send();
  return xmlhttp.responseText;
};

var slideshow = remark.create();
```

Then, in your slideshow, `![:include](1.md)` will be replaced with the contents of `1.md`. For security reasons, most browsers denies filed to be loaded from the local filesystem like this. So if you're running your slideshow from a local file, this won't work. You have to serve the file via a web server.

**Comment by gnab** [comment]
@aldarionsevero If you're having any issues with this, please open a new issue.

**Comment by mhavo** [comment]
Include is including properly only one plain slide inside md. Only the first is included. If there is more slides they are left out. And if there is images inside slides there will be an error.

**Comment by mdreier** [comment]
The reason for that is in line 76ff. of parser.js

```JavaScript
var value = macro.apply(token.obj, token.args);
if (typeof value === 'string') {
   value = self.parse(value, macros);
   appendTo(stack[stack.length - 1], value[0].content[0]);
}
```

So the complete return value of the macro will be parsed, but only the first content element of the first slide will be added to the current slide element. In many cases this may be appropriate, but when including complete files it should rather be adding these slides to the stack

```JavaScript
slides.push(stack[0]);   //End current slide
slides.push(...value);   //Push slides from include
stack = [createSlide()]; //Start next slide
```

Maybe only do this if more than one slide was returned from the parsed value to not break existing behavior.
