### ISSUE TITLE
Chrome 38 Print Margins

### ISSUE THREAD

**Issue by eljefe6a** [gnab/remark#151]
It looks like Chrome 38 doesn't print to PDF properly now. I've checked my presentations that haven't changed and they have the same issues.

The pages' margins are ~3em to the right and the bottom margins are ~3em below. My page numbers (bottom right aligned) don't even show up now.

The full Chrome version is Version 38.0.2125.101.

**Comment by szpak** [comment]
The mentioned solutions don't work in Chrome 40 :(.

**Comment by eljefe6a** [comment]
I stopped trying to create a workaround for each version of Chrome. I created a VM image of Ubuntu. I installed the latest version of Chrome 37 on it. Chrome doesn't automatic update on Linux and you can depend on Chrome 37 to always work.

**Comment by szpak** [comment]
Good idea, thanks. I dug out old VM with Chrome 34 and it worked fine.

**Comment by brunetto** [comment]
Do you really are comfortable with using a VM just to print a slideshow?
Is there a way to understand the origin of this problem?

**Comment by brunetto** [comment]
In alternative you can install chromium-browser v37... it's the same as chrome and you don't need the VM anymore.

**Comment by brunetto** [comment]
It works!!

http://stackoverflow.com/questions/9540990/using-chromes-element-inspector-in-print-preview-mode

**Comment by ryaneberly** [comment]
Adding 
.remark-slide-scaler {
    -webkit-transform-origin: initial;
}
to my <style/>
worked for me on chrome 44.

**Comment by tbrannam** [comment]
@ryaneberly is right - works on Mac Chrome 47

Can change to be only be changed if using print function.   Tested in Safari 9.0.1 as well

    @media print {
      .remark-slide-scaler {
	    -webkit-transform-origin: initial;
      }
    }

**Comment by gnab** [comment]
@tbrannam's pull-request has been merged and will hopefully be included in a release soon.

**Comment by gnab** [comment]
The pull has been released in version 0.13.

This topic seems to be a never ending story, but I'm closing in now, waiting for the next printing issue to pop up shortly...

**Comment by eljefe6a** [comment]
Neither the CSS change nor using 0.13 worked for me. I'm using Chrome 47 on a Mac too.

**Comment by nealmcb** [comment]
Note that [DeckTape](https://github.com/astefanutti/decktape) is recommended for generating the PDF, as recommended in the [Remark Readme](https://github.com/gnab/remark#printing). Worked for me, after failing with Chrome Version 58!

**Comment by utdrmac** [comment]
@nealmcb Thanks for that! Working great for me. Any idea how I can join multiple rendered PDFs together into one massive one?

**Comment by szpak** [comment]
@utdrmac There are at least a few solutions for Linux. AFAIR I've been using [pdfunite](http://manpages.ubuntu.com/manpages/trusty/man1/pdfunite.1.html) and it worked fine (in my case).
