### ISSUE TITLE
Modifying Slide Content With Events

### ISSUE THREAD

**Issue by eljefe6a** [gnab/remark#153]
I tried to use the beforeShowSlide and showSlide to modify the slide's content. I modified the slide's slide.content array to something different. The changes I made in the slide.content are not reflected in the HTML. Are these events not made to change slide HTML?

Also, the https://github.com/gnab/remark/wiki/Configuration#api in the Slide section needs to be updated. For example, there isn't a slide.source anymore.

**Comment by gnab** [comment]
Sorry for the late reply (as usual).

The changes you make to that structure (the slide.content) is only read once when the slide is rendered the first time, so they are not suited for updating slide contents I'm afraid. You can however change the slides' HTML directly.
