### ISSUE TITLE
Different padding for highlighted code lines in 0.6.5 and 0.7.0

### ISSUE THREAD

**Issue by szpak** [gnab/remark#154]
Given the following Markdown/Remark code:
```
    ```
    * @Parameters({"1, 2, 3", "2, 3, 5", "3, 5, 8"})
    ```
```
In 0.6.5 it was rendered as:
```
<div class="remark-code-line remark-code-line-highlighted"> @Parameters({"1, 2, 3", "2, 3, 5", "3, 5, 8"})</div>
```
in 0.7.0:
```
<div class="remark-code-line remark-code-line-highlighted">  @Parameters({"1, 2, 3", "2, 3, 5", "3, 5, 8"})</div>
```
(one leading space more)

It is not a problem with modify the slides with highlighted lines, but I wonder if it is a behavior which will be continued in the further Remark versions or it is a temporal distortion and will be reverted.

**Comment by gnab** [comment]
Sorry for the late reply. If this is still the case, I guess it's safe to say it is not a temporal distortion ;)
