### ISSUE TITLE
Randomizing Slides

### ISSUE THREAD

**Issue by mettamatt** [gnab/remark#157]
Is there an easy way to randomize the order of the slides? I created a for loop, but it doesn't seem to work. 

```
var slideCount = slideshow.getSlideCount();
  for(i=0; i<slideCount;i++) {
    var rand = Math.floor(Math.random() * slideCount) + 1;
    slideshow.gotoSlide(rand);
    slideshow.pause();
}
```

Thoughts?

**Comment by gnab** [comment]
I guess you are not impressed by my response time :p

The `pause` function is/was meant for pausing the timer, as far as I can recall, but I'm not sure. Anyways, you can do like in this [demo](http://jsfiddle.net/4wa3kqtt/).

It navigates to a random slide, waits for a second, and navigates again, as many times as there are slides.

**Comment by mettamatt** [comment]
Thanks Peter. It'll be good to know for next time. :)
