### ISSUE TITLE
Reference-style links not working

### ISSUE THREAD

**Issue by booch** [gnab/remark#161]
The following 3 examples should all create the same links. Only the first one works; the others just output the square brackets as if they didn't have any special meaning.

```
1. [Remark][1]
2. [Remark]
3. [Remark][Remark]

[1]: https://github.com/gnab/remark
[Remark]: https://github.com/gnab/remark
```

In GitHub's Markdown, these render as:
1. [Remark](https://github.com/gnab/remark)
2. [Remark](https://github.com/gnab/remark)
3. [Remark](https://github.com/gnab/remark)

**Comment by tbfe-de** [comment]
I was also surprised by this!

For those of us having started heavy use of remark.js for their presentations, it would be helpful if there were a process to insure essential things like these don't break. Maybe by having some (TDD-style) automated tests that are run when there are changes in (or of) libraries that remark.js depends on. (Are there MD test-suites?)

**Comment by booch** [comment]
This is working fine now in the current version.
