### ISSUE TITLE
some keyboard shortcuts are broken

### ISSUE THREAD

**Issue by brunetto** [gnab/remark#171]
I found the `w` (pause/resume) and the `b` (blackout mode) shortcuts not working.

**Comment by gnab** [comment]
As pointed out by @danfarrow, 'b' blacks out a normal-mode slideshow or the audience's cloned slideshow but not the presenter-mode slideshow.

'w' is no longer wired up on the code and I cannot see the use of this, so I'm removing it.

**Comment by gnab** [comment]
The 'w' shortcut has been removed in version 0.10.1.
