### ISSUE TITLE
remark in a CDN

### ISSUE THREAD

**Issue by juanpabloaj** [gnab/remark#183]
Hi,

why don't host remark in a CDN ? like https://cdnjs.com/

**Comment by gnab** [comment]
Serving from GitHub seems to work okay for most people, so I'm closing off this one for now.

**Comment by mizunashi-mana** [comment]
@gnab Hi!

I would like you to add support cdn.

Now, we can use https://gnab.github.io/remark/downloads/remark-0.13.min.js or http://remarkjs.com/downloads/remark-0.13.min.js as external resource.
However, remarkjs.com seems not to have support for https, and github don't support cros.

I cannot find any solutions.  If we don't have any solutions, we should reopen this issue.
https://cdnjs.com/ support seems very easy for me.  If you say ok, I will request in cdnjs and hope your help when there are troubles uploading this library in cdnjs.

* ref: https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

**Comment by gnab** [comment]
remarkjs.com is now available over HTTPS, but remark has also been added to cdnjs via https://github.com/cdnjs/cdnjs/issues/10062
