### ISSUE TITLE
create pdf from remark.js output

### ISSUE THREAD

**Issue by bastelfreak** [gnab/remark#186]
Hey guys,

this is more of a question than an issue, do you have any recommended way to create a pdf instead of html output? Or any way to migrate the html into pdf?

**Comment by William-Yeh** [comment]
See [#issue 50](https://github.com/gnab/remark/issues/50)

**Comment by gnab** [comment]
Converting to PDF is primarily supported via Chrome's Print to PDF feature. This worked perfectly initially, but currently you need to tweak a bit to have the PDF look as expected. Please see #50 as pointed out by @William-Yeh .
