### ISSUE TITLE
Firefox scroll wheel not working

### ISSUE THREAD

**Issue by vodou** [gnab/remark#187]
I can view presentations in Firefox, and use the arrow keys to move back and forth, but the scroll wheel does nothing. I can also advance by changing the number in the URL (eg, `http://example.com/presentation#5` to `...#6`), but obviously that's tedious.

I'm using Firefox 34.0 (Linux).  I tried it with a clean profile (no extensions), and have also tested in 34.0.5 (Windows) and 35.0 (Windows). None of them use the scroll wheel.

Chrome 39.0.2171.95 (Linux) allows me to use the scroll wheel.

This is a very minor issue -- to me, at least -- but I thought you might want to know about it.

**Comment by gnab** [comment]
The fix for this is included in the recently released version 0.10.0.
