### ISSUE TITLE
Error parsing nested brackets

### ISSUE THREAD

**Issue by Loreia** [gnab/remark#189]
Hi and thanks for a great presentation tool.
I have a problem with brackets **[ ]** within slide (my slides are written as markdown text). If brackets are not "closed", meaning opening bracket immediately followed by a closing one, then the whole *.right-column[ ]* sections breaks.

To reproduce the issue, use your example presentation (http://gnab.github.io/remark/#3), and in any slide add one opening brace in *.right-column[ ]* section. For example add this to the third slide:
- Break slide by inserting opening bracket [              

After refresh, slide looks like this: 
![image_76](https://cloud.githubusercontent.com/assets/1406771/5792650/ff342256-9f23-11e4-8175-60343fc46610.png)

So far, the only workaround I have found is to write "invisible" (white on white) closing bracket. Is there another way to work around this? I am writing a small BASH tutorial, and opening bracket **[** (test command) gets used *a lot*. 
I would love to solve this in a more "elegant" way that writing invisible closing brackets.

Again, thanks for a great tool and thanks in advance for any help on this.

**Comment by gnab** [comment]
Sorry for the extremely late response.

You can escape the opening bracket using `&amp;#91;`, like in [this demo](http://jsfiddle.net/pmpj26aw/).

**Comment by Loreia** [comment]
Actually, you timing is great. I am working on new tutorial (this time about Python) and this will definitely help. Thanks.

**Comment by gnab** [comment]
Great! Closing this one off then.

**Comment by Loreia** [comment]
I added a section in wiki explaining this: https://github.com/gnab/remark/wiki/Markdown#content-classes

**Comment by gnab** [comment]
:+1:
