### ISSUE TITLE
Better support for lists with items shown on click

### ISSUE THREAD

**Issue by szpak** [gnab/remark#191]
In my presentation I need to have on a few slides lists (unordered or ordered) in which the following items should be shown on a click. Currently it can be done with a duplication of all previous point on every slide, but it is hard to maintenance in case of changes. There is `layout`, but only header occurs on every slide.

I don't have a clear idea how could it implemented, but It would be good to have a separate mechanism to allow to easily add those list (e.g. a list wrapped up with some magic tag/style/whatever which is rendered as a separate slides with just one mire item added on each slide - it should cover the base case).

So the simple list (with some special marker):
```
# Summary
- Point 1
- Point 2
- Point 3
```
would be rendered (in html) as the 3 separate slides looking the same as:
```
# Summary
- Point 1
---
# Summary
- Point 1
- Point 2
---
# Summary
- Point 1
- Point 2
- Point 3
```

**Comment by gnab** [comment]
Is this what you are looking for?

https://github.com/gnab/remark/wiki/Markdown#incremental-slides

**Comment by szpak** [comment]
Definitely... Thanks for a tip.
