### ISSUE TITLE
More control over the timer

### ISSUE THREAD

**Issue by astorije** [gnab/remark#195]
At the moment:
- The timer starts as soon one changes slide
- It is possible to reset the timer by pressing `t`. This also stops the timer.

I noticed that this makes the timer often unusable for short or very short presentations (like lightning talks, where 20 seconds matter).

It would be nice to have complete control over the timer, such as (throwing ideas here, more than anything else):
- Ability to start it manually, so that staying 5 minutes on the first slide counts. Right now one has to go super quickly to the second slide and back to the first one to emulate the behavior.
- #171 resulted in completely remove pausing/resuming the timer, which might actually be nice. Not a killer feature, but nice to have IMO
- This might look over the top but, using the [History API](http://www.w3.org/TR/2014/REC-html5-20141028/browsers.html#history) (which I think you already use), the current time could be kept in the URL so that refreshing would not restart the timer! At the moment, pressing `t` and refreshing the page have similar result.
- And since I am dreaming and suggesting crazy things, having a decreasing timer would be the bomb. For example: starting `remark` with `remark.create({ timer: { start: 20 * 60, critical: 120 } });` would start a 20-minute decreasing timer that changes to red when the 2-minute-left bar is reached.
- The `timer: { ... }` object could also contain other pieces, like the ability to disable `t` to avoid accidents, or set the timer as increasing/decreasing, ...

**Comment by gnab** [comment]
Sorry for the late reply. I like you suggestions - the current timer implementations is rather limited and annoying at times. Will look into adding some of this when I have time available.

**Comment by astorije** [comment]
Thanks @gnab! Feel free to discuss them here and, who knows, with extra free time coming from nowhere I might even contribute :-)

**Comment by utdrmac** [comment]
+1 for all this!

**Comment by HIC-SamT** [comment]
Love the above, along with the ability to set a time interval per slide or per slide template would be amazing @gnab :)

**Comment by rauschma** [comment]
Additionally, I’d love to be able to switch off the timer. It’s distracting if you don’t need it.

I also find seeing the seconds distracting. Maybe minutes-only as an option?

**Comment by dvberkel** [comment]
I came here to find out how to reset the timer and loved this feature request. Is somebody working on it? Otherwise I would like to take a look. At least for the starting/pausing feature

**Comment by tripu** [comment]
@dvberkel, given limited time from collaborators of this project to work on this feature, we welcome that PR!

**Comment by peterj** [comment]
@dvberkel I know it's been a while, but you would you be interested in working on this?

**Comment by dvberkel** [comment]
@peterj I am still interested in this.

I must have missed @tripu comment that a PR was welcome. I will take some time this weekend to make an initial contribution.

**Comment by peterj** [comment]
I am closing this as it was implemented by @dvberkel!
