### ISSUE TITLE
Unwanted behavior with lists and sub-lists spread over multiple slides

### ISSUE THREAD

**Issue by astorije** [gnab/remark#196]
When using the following code (blank lines are on purpose):

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Test slideshow</title>
  </head>
  <body>
     <textarea id="source">
- Item two
  - Sub-item

--

- Item three
    </textarea>
    <script type="text/javascript" src="http://remarkjs.com/downloads/remark-0.10.2.min.js"></script>
    <script type="text/javascript">remark.create();</script>
  </body>
</html>

```

The slide first shows:

> - Item two
>   - Sub-item

Then, when displaying the next item shows:

> - Item two
> 
>   - Sub-item
>
> - Item three

This makes the sub-item "jump", move down by one line, when going the the second slide. It's actually harder to explain that to try out :)

While typing this issue, I realized that it is most likely the standard behavior of a Markdown generator, but when showing the transition on the screen, it looks pretty bad.
Is there any way to fix this without butchering the markup? Removing blank lines around `???` (when used) for example would give an obscure source, I think.

**Comment by gnab** [comment]
If you remove the empty line after the incremental slide separator it works as expected:

```
- Item 1
  - Subitem 1

--
- Item 2
```
