### ISSUE TITLE
scroll and click options do not affect the navigation ability

### ISSUE THREAD

**Issue by astorije** [gnab/remark#197]
Assuming the [configuration page](https://github.com/gnab/remark/wiki/Configuration) is up-to-date, that `scroll` controls the mouse scroll, that `click` controls the mouse click, and considering the following minimal example:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Test slideshow</title>
  </head>
  <body>
     <textarea id="source">
Slide one
---
Slide two
---
Slide three
    </textarea>
    <script type="text/javascript" src="http://remarkjs.com/downloads/remark-0.10.2.min.js"></script>
    <script type="text/javascript">
      remark.create({
        scroll: false,
        click: true
      });
    </script>
  </body>
</html>
```

The slides can still be navigated using the mouse/touchpad scroll, and not navigated using the mouse/touchpad click.

It might be 2 independent issues but I figured it would be more better to gather them on the same issue.

**Comment by gnab** [comment]
Sorry for the late reply.

You missed the `navigation` level of the configuration object. It's supposed to be like this:

```javascript
remark.create({
  navigation: {
    click: true, 
    scroll: false
  }
});
```

**Comment by astorije** [comment]
Woops, thanks!
