### ISSUE TITLE
Add direction indication when changing slide

### ISSUE THREAD

**Issue by partageit** [gnab/remark#206]
Hello,
First, thank you for this tool, it is really easy to use :)

I think that it would be nice to know the direction when changing slide, adding a class near the remark-fading one, for example remark-forward when the new slide number is greater than the previous, else remark-backward.

It would be useful when writing CSS transitions, sliding the slide to the left or to the right when needed.

David

**Comment by junderhill** [comment]
Do you like an arrow that shows for a second or two then fades out, indicating left for previous and right for next?

**Comment by partageit** [comment]
For example, this slideshow:
http://partageit.github.io/vegetables/index-slideshow.html
The transition effect is based on remark-fading. The slide fall when I go forward, and I would like to make it 'unfall' when I go backward.

It is the same to make it slide to the left or slide to the right.

And I think that new classes remark-forward and remark-backward added and removed with remark-fading would ease transition writing.

David

**Comment by partageit** [comment]
In fact, it is possible with CSS, and the ~ selector:
When going forward:
.remark-slide-container {
	right: 1000px;
}
And backward:
.remark-visible ~ .remark-slide-container {
	right: -1000px;
}
Thank you :)

David
