### ISSUE TITLE
background-repeat doesn't work since 0.6.0

### ISSUE THREAD

**Issue by unrealsolver** [gnab/remark#211]
I've tried to use `background-image: url("some.pmg")`
But background image doesn't have `no-repeat` css. I've tried different versions, and no version above 0.6.0 works correctly.

**Comment by jberkus** [comment]
Verified, this is broken.  No idea how to fix it.

**Comment by gnab** [comment]
Seems to be working fine now. 

[Demo](https://jsfiddle.net/qytg78tp/)

**Comment by remimarenco** [comment]
It doesn't seem to work for me too. In your example @gnab , it shows "no-repeat" as raw text.

On my side, if I set this in my .md:

```
background-image: url(images/app_architecture/job_management.png)
background-position: center;
background-repeat: no-repeat;
background-size: contain;
```

I have this as output in my *.html:

```html
<div class="remark-slide-content inverse center middle hljs-default"
style="background-image: url(&quot;images/app_architecture/job_management.png&quot;);
background-size: 908px 246.495px;
background-position: 50% 217.253px;">
<div class="remark-slide-number">22 / 85</div>
</div>
```

Am I misusing the feature?
