### ISSUE TITLE
Export to PDF

### ISSUE THREAD

**Issue by davidonlaptop** [gnab/remark#212]
It would be awesome to be able to export a Remark presentation to PDF or other formats.

**Comment by junderhill** [comment]
It would! This is discussed in issue #186 and issue #50

**Comment by gnab** [comment]
As @junderhill says, this is already discussed in #186 and #50. Export to PDF was implemented via Chrome's Print to PDF feature when Chrome was in version 30 something, but recently the print implementation in Chrome has changed, requiring a bit of tweaking to get the slides to fit the sheet. I haven't looked into updating the implementation yet, and it seems it still changes with every new release of Chrome, so until becomes more stable it is going to be remain an experimental feature.

Closing this one as a duplicate.
