### ISSUE TITLE
Feature request - hiden class details when viewing markdown

### ISSUE THREAD

**Issue by johntrandall** [gnab/remark#215]
Hello. I just discovered remark. It is awesome. Thanks for making it. 

I'm trying to kill two birds with one stone, and have a markdown file in a particular folder on github. (Such as a "how_to_use_this_testing_suite" in our "tests" folder, but also use that markdown file to serve up a slideshow via HTML. It is wonderful. 

The only catch is that when I assign classes to either a slide or a particular element, those class assignments are visible when I view the markdown, either on Github, or in Mou, or elsewhere. (Github being the most important.) Is there any way to get around this beyond just not using classes? 

If not, I'm guessing there might be a way to denote classes that remark uses in a way that markdown ignores them. Perhaps by hiding the class allocations in markdown comments? 

Apologies in advance if I'm missing something obvious here.

**Comment by gnab** [comment]
Sorry for the slow reply.

This is indeed a handy feature request. I'm now added support for specifying slide properties inside HTML comment tags. Given the current implementation, the easiest solution was to require one HTML comment tag per slide property, so you'll have to do like this:

```
<!-- class: middle, center -->
<!-- name: agenda -->

# Slide with hidden slide properties outside of remark
```

Functionality will be available in the upcoming 0.11 release.

**Comment by gnab** [comment]
Version 0.11 which fixed this has now been released.

**Comment by johntrandall** [comment]
excellent!
