### ISSUE TITLE
Insert line breaks

### ISSUE THREAD

**Issue by enrico16** [gnab/remark#216]
Sometimes I'd like to vertically space two elements in a slide.
I found out this is possible by typing `<br>`, is there a way to do this in pure markdown?

**Comment by gnab** [comment]
What kind of elements are you trying to add space between?

Works fine with `<br />`, but you may need a few to see the effect:

http://jsfiddle.net/re9r9zv2/

**Comment by enrico16** [comment]
This example should illustrate what I'm after:

```markdown
## Title

--

- First bullet

--

- Second bullet

--

- Third bullet

--

<br>
I want this line to be more vertically spaced from the last bullet point.
Using `<br>` works, but is there a way to use markdown rather than HTML?

---
```
