### ISSUE TITLE
Impossible to use with NPM as the asset manager?

### ISSUE THREAD

**Issue by tbranyen** [gnab/remark#217]
Seems very, very odd to ignore `out` in the `.npmignore` file.  Without that folder, attempting to install any tag using NPM will result in a completely unusable folder full of source files.

Would you consider removing the out folder?

**Comment by gnab** [comment]
Where did you see the `.npmignore` file?

During deploy, the `out` folder is included in the corresponding tag to enable installing via Bower. I've never looked into deploying to NPM, but I guess it could easily be supported.

**Comment by tbranyen** [comment]
Oh right, @gnab the `.npmignore` if not present, is automatically assumed to be `.gitignore` where `out` is currently blacklisted.  Could you add in an `.npmignore` (or accept a PR that adds one) to whitelist the `out` directory?

**Comment by gnab** [comment]
Sorry for the late reply. All PRs are more than welcome ;)
