### ISSUE TITLE
Slide Steps Removed?

### ISSUE THREAD

**Issue by eljefe6a** [gnab/remark#218]
Was the slide step code talked about in #56 removed? A search of the repo for the word "step" comes up with nothing. Adding a `.step()` method to a slide results in an error.

Was the method renamed?

**Comment by gnab** [comment]
I found the initial implementation a bit rough around the edges, and the contributor and I kind of never agreed on how to handle the initial step. The functionality is more or less implemented in the `steps` branch, but has never made it into master. Would be cool to have, though.

**Comment by eljefe6a** [comment]
I'm starting to get asked about animations in my slides. I'm thinking that having macros with animations would be very interesting. I looked into some of the things JQuery can do out of box and they'd be interesting macros.

**Comment by gnab** [comment]
Please re-open if still relevant.
