### ISSUE TITLE
Local video player

### ISSUE THREAD

**Issue by rififi** [gnab/remark#219]
Hi,

I wonder how I could add a video in my presentations. I have one constraint however: the video is not on a server (not on youtube, not elsewhere). I can't (I mean, I don't want to) upload it on any server. I want to keep it local. So I guess I must use an embedded player.Do you have any idea about how I could do that ?

**Comment by gnab** [comment]
Did you try the HTML5 [video](http://www.w3schools.com/html/html5_video.asp) tag?

You may use more or less any HTML you want in your slides, to do stuff Markdown doesn't let you do.

**Comment by gnab** [comment]
Please re-open if this is still unresolved.
