### ISSUE TITLE
Broken code block parsing

### ISSUE THREAD

**Issue by edom** [gnab/remark#220]
In a code block like this:

```
c f a b = a `f` b
```

Remarkjs swallows the backticks to highlight the second f.

GitHub doesn't do that, so if the name is faithful, GitHub Flavored Markdown shouldn't do that either.

It should output the backticks verbatim.

All of these fail:

```haskell
&#140;f&#140;
``f``
\`f\`
```

Also, because backtick cannot be escaped, there is no way to illustrate a code block inside a code block.

```
\```
wrong
\```
```

I'm using Remarkjs to present Haskell to beginners. This is fatal.

There is a workaround:

    <script>
        /* WORKAROUND */
        window.onload = function () {
            document.getElementsByTagName('pre').forEach(function (e) {
                e.innerHTML = e.innerHTML.replace(/\\\`/g, '`');
            });
        };
    </script>

**Comment by gnab** [comment]
As of version 0.11, via #192, this behavior is configurable and disabled by default.

**Comment by gnab** [comment]
Version 0.11 which fixed this has now been released.
