### ISSUE TITLE
Update highlight.js (bug in Java highlighting)

### ISSUE THREAD

**Issue by mweberUKL** [gnab/remark#221]
The version 8.0 of highlight.js using in the current version of remark has a bug with the Java highlighting. A leading `class` keyword is not highlighted correctly, only if a modifier like `public` is used in front of it.

There may be other issues that have been resolved upstream. The current version of highlight.js is 8.5. Remark currently works without modification with version 8.3 (just change the version number in line 20 in the `make.js` file). I also tried to switch to version 8.5 but with less success (`Error: Parsing file remark/src/remark/highlighter.js: Line 744: Unexpected token ;` while building remark with `make`).

**Comment by gnab** [comment]
Version 0.11 which fixed this has now been released.
