### ISSUE TITLE
Templated slides should be considered only one slide

### ISSUE THREAD

**Issue by c-b** [gnab/remark#223]
If I have a slide like this:

```
# Agenda

1. Introduction

--

2. Deep-dive

--

3. ...
```
It should count as a single slide, but it does not. For example, in the slide counter, it will show up as 3 slides.

**Comment by grabbou** [comment]
True. Otherwise, when trying to print to PDF, I get so many duplicated slides that it even does not make sense!

**Comment by gnab** [comment]
The wiki documentation is not up-to-speed on this yet, but #177 added support for excluding single slides from being counted as well as incremental slides, which is what you get when using the `--` slide separator.

**Comment by gnab** [comment]
I've added a section about the [count](https://github.com/gnab/remark/wiki/Markdown#count) slide property to the wiki now.

**Comment by grabbou** [comment]
Thanks, can be closed then.
