### ISSUE TITLE
Scale svg with css

### ISSUE THREAD

**Issue by brunetto** [gnab/remark#228]
Hi!
Is there a way to insert a svg (I can do that with `![name](./name.svg)`) and make it scale correctly to fill the available space? I always have to resize the svg in inkscape... I can't find a way to do this via css. But for example centering the image works via `.center[![name](./name.svg)]`.

**Comment by gnab** [comment]
This probably requires some JavaScript, and you need to calculate what you call the available space - I'm assuming there may be other content both before and after the image.

A simple work-around however, is to simply wrap set the width of the picture to some percentage - tweaking it manually until it fits, e.g.:

```
Some content

<img src="name.svg" style="width: 50%" />

More content
```

You can also [create a macro](http://jsfiddle.net/82hzz7pq/) that creates the `img` tag for you and applies a given width.

**Comment by brunetto** [comment]
Great!! It works!! I tried with Javascript but I didn't succeed!!

Thanks!!
