### ISSUE TITLE
how to adjust the font of a specific sentense/paragraph/word ?

### ISSUE THREAD

**Issue by pinggit** [gnab/remark#230]
is it possible?
currently it's automatic, and I want to specify some text to be bigger or smaller...

**Comment by gnab** [comment]
What you are looking for is [content classes](https://github.com/gnab/remark/wiki/Markdown#content-classes). You can wrap content (a word, sentense or paragraph for instance) and apply a CSS style to the selected content:

```
Some text is .large[larger] and some is .small[smaller].
```

Then, in the HTML page, you simply have to append a `<style>` block defining the CSS styles for the `large` and `small` classes:

```html
<style>
  .large { font-size: 130% } 
  .small { font-size: 70% }
</style>
```

Demo: http://jsfiddle.net/w4cmqaoa/

**Comment by pinggit** [comment]
oh I see...this is really nice and simple. thanks for the example!

**Comment by nchammas** [comment]
@gnab - Is there a way to increase the default font size for the whole presentation?

I'm using GistDeck, so I'm not sure if there's a way to do something like that strictly from within the Markdown hosted on Gist.
