### ISSUE TITLE
how to step a slides?

### ISSUE THREAD

**Issue by pinggit** [gnab/remark#231]
is it possible?
I searched over many discussions and still don't know how to do it in my remark slides...
please show me a snippet of examples....
appreciate it.

**Comment by gnab** [comment]
Do you mean to go to the next slide?

```
var slideshow = remark.create();
slideshow.gotoNextSlide();
```

Read more about [navigation](https://github.com/gnab/remark/wiki/Configuration#navigation).

**Comment by pinggit** [comment]
thanks. I meant "incremental" slides show.

but regardless, I'm curious about where I put these codes ? anywhere in the
whole slides? or put in any specific slide?
do you have a complete working sample?

this may sounds idiot , but I'm really confused without an example when I
look at the manual...

thanks alot.

**Comment by mathiasbynens** [comment]
I think @pinggit means, how to make a slide where each item (i.e. paragraph, bullet point, or whatever) appears one by one, i.e. after clicking next each time, without duplicating the content.

Consider the following slide:

```
---
## My slide

This is a paragraph.

This is another paragraph.

* This is a bullet point.
* This is another bullet point.
---
```

The initial view would be just the title, then when clicking next the first paragraph appears, then the second, etc.

One way to do it is to implement another custom Markdown syntax, e.g. `-` for slide sections that should appear separately:

```
---
## My slide

This is a paragraph.

--

This is another paragraph.

--
* This is a bullet point.
--
* This is another bullet point.
--

---
```

**Comment by mathiasbynens** [comment]
Hmm, there seem to be some mentions about “incremental slides” in the wiki… How does this feature work?

**Comment by mathiasbynens** [comment]
Aha, found it! All you have to do is use the `--` separator.

Perhaps it would be nice to add an example to the example slide show.
