### ISSUE TITLE
Add syntax highlighting for all languages supported by highlight.js

### ISSUE THREAD

**Issue by aochagavia** [gnab/remark#233]
Currently, the only way to have syntax highlighting for some new languages like `D`, `Rust` or `Go` is to modify the source code. It would be nice to support this languages out of the box, or to allow the user to provide its own `highlight.js` with support for the languages he needs.

**Comment by gnab** [comment]
Embedding language syntaxes into remark currently requires modifying the configuration and building.

Using an external language definition/syntax however, is pretty easy, and is done in the [remark slideshow](https://github.com/gnab/remark/blob/gh-pages/index.html#L463-466) to include a [custom markdown syntax](https://github.com/gnab/remark/blob/gh-pages/remark.language.js).

Basically, you can access highlightjs via the `remark.highlighter.engine` property, and register new languages before creating the slideshow.

**Comment by aochagavia** [comment]
This is perfect! Thanks for your answer
