### ISSUE TITLE
Widescreen Slides

### ISSUE THREAD

**Issue by marktyers** [gnab/remark#238]
Is it possible to render a slideshow 16:9 format please?

**Comment by gnab** [comment]
Yes, when the call to `remark.create()` can take an options object, which supports a `ratio` option, which is by default `4:3`, that may be set to whichever ratio you'd like, e.g.:

```javascript
var slideshow = remark.create({ ratio: '16:9' });
```

Wiki: https://github.com/gnab/remark/wiki/Configuration#general

**Comment by marktyers** [comment]
Thanks.
