### ISSUE TITLE
Can remark be packaged for offline Viewing?

### ISSUE THREAD

**Issue by ideoplex** [gnab/remark#244]
I saw the previous question about offline authoring/presenting. I'm interested in the slightly different case of sending a remark.js presentation to someone who may be reading it offline.

I understand that I'd need to switch the fonts. But my attempt to simply embed the javascript did not go well and I'd rather avoid hitting my head against a wall if this is doomed to failure.

**Comment by gnab** [comment]
It depends what you mean by packaged. You can easily download all resources and distribute alongside your presentation. For embedding remark into the slideshow to not need the external remark.js file, you can use the [boilerplate-single.html](https://raw.githubusercontent.com/gnab/remark/develop/boilerplate-single.html) slideshow template that has remark embedded in it. If you want to embed fonts and images, you can look into [data-uris](https://css-tricks.com/data-uris/). Ultimately, you should end up with only a single HTML file.

**Comment by ideoplex** [comment]
boilerplate-single.html was what I was looking for.

Thanks
