### ISSUE TITLE
Wrong version number

### ISSUE THREAD

**Issue by rolegic** [gnab/remark#245]
Version number has been added in release `v0.11.0`, but unfortunately, value is not the right one:
- expected: `0.11.0`
- current: `0.10.2`

See [resources.js](https://github.com/gnab/remark/blob/develop/src/remark/resources.js):
```javascript
/* Automatically generated */

module.exports = {
  version: "0.10.2",
  ...
```

**Comment by gnab** [comment]
Yes, but this is only in the source code. The built/bundled `remark.min.js` file has the correct version. If you navigate to http://remarkjs.com, open the developer tools console in your browser and enter `remark.version` you'll get `'0.11.0'` back.

**Comment by gnab** [comment]
I updated the source, so now everything should be in sync.

**Comment by rolegic** [comment]
OK
Thanks again for this great tool!
Le 27 juil. 2015 6:57 PM, "Ole Petter Bang" <notifications@github.com> a
écrit :
