### ISSUE TITLE
Code line highlight does not work in version 0.11.0

### ISSUE THREAD

**Issue by OlgaMaciaszek** [gnab/remark#251]
The code line highlight feature with "*" seems to have stopped working in the latest version. 

For this sample code snippet:

```groovy
	buildscript {
		repositories {
			mavenCentral()
			mavenLocal()
		}
		dependencies {
	* classpath 'io.codearte.accurest:accurest-gradle-plugin:0.7.1'
		}
	}
```
when script src is set to 0.10.2:
```html
<script src="https://gnab.github.io/remark/downloads/remark-0.10.2.min.js">
```
the highlight works correctly.

With the following setting:
```html
<script src="https://gnab.github.io/remark/downloads/remark-0.11.0.min.js">
```
it does not.

**Comment by gnab** [comment]
This was disabled by default in #192, but may be enabled using the [highlightLines](https://github.com/gnab/remark/wiki/Configuration#highlighting) configuration option.

**Comment by OlgaMaciaszek** [comment]
Ok. Thanks.
