### ISSUE TITLE
Comments?

### ISSUE THREAD

**Issue by spitters** [gnab/remark#263]
Sorry, I think I've tried most options and couldnt find this in the docs.
Does remark support comments? These general md-[solutions](https://stackoverflow.com/questions/4823468/store-comments-in-markdown-syntax) do not seem to work.

**Comment by dirkhusemann** [comment]
Hmm. I'd go for a CSS version:

    .comment[Et centerum censeo Catharginem esse delenda]

and defining `.comment` as non-displaying in your CSS:

    .comment {
        display: none;
    }

Yep, not as nice as having `//´ or something like it, but should be easy to implement, and, yes it still shows up as a comment in the HTML source.

**Comment by jpetazzo** [comment]
I personally use HTML comments:

```
<!-- blah blah blah -->
```

**Comment by gnab** [comment]
You could simply use the presenter notes section, following a `???` separator, as mentioned [here](https://remarkjs.com/#15).

**Comment by abelards** [comment]
There are three workarounds, and I've already used two of them, so I'm closing the issue :)
