### ISSUE TITLE
Can I put AdSense code into a slide

### ISSUE THREAD

**Issue by martinhbramwell** [gnab/remark#264]
I'm trying to put a "skyscraper" ad in the left column, like this ...

    layout: false
    .left-column[

      ### PART B Introduction
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <ins class="adsbygoogle"
         style="display:inline-block;width:300px;height:600px"
         data-ad-client="xx-pubic-7072962426749"
         data-ad-slot="2025551212">
    </ins>
    <script>(adsbygoogle = window.adsbygoogle || []).push({});</script>
    ]
    .right-column[

          ::
          ::
          ::

... but it seems to be eliminated completely.

Is there a way to do it?

**Comment by gnab** [comment]
I'd try to only have the `<ins>` block inside a slide, and to move the two `<script>` blocks last in `<body>`, _after_ the `<script>` block containing the `remark.create()` call.
