### ISSUE TITLE
smartypants support?

### ISSUE THREAD

**Issue by dflock** [gnab/remark#266]
remark seems to currently use the marked markdown compiler - which seems to support smartypants. This is from the bottom of remark.js:

```javascript
/**
 * Options
 */

marked.options =
marked.setOptions = function(opt) {
  merge(marked.defaults, opt);
  return marked;
};

marked.defaults = {
  gfm: true,
  tables: true,
  breaks: false,
  pedantic: false,
  sanitize: false,
  smartLists: false,
  silent: false,
  highlight: null,
  langPrefix: 'lang-',
  smartypants: false,
  headerPrefix: '',
  renderer: new Renderer
};
```

I've tried doing this in my slides but it doesn't seem to do anything:

```html
    <script type="text/javascript">
      var slideshow = remark.create({
        sourceUrl: 'slides.md',
        highlightStyle: 'monokai',
        smartypants: true
      });
    </script>
```

For example, this content renders exactly as shown - no apparent smartypants processing:

```markdown
---

# What is User Testing & how do you do it?

This is a double dash -- right there.

And here are some "quotes".

---
```

Am I doing something wrong, or do I need other dependencies installed for this to work? I get no errors in the browser console. This is using remark 0.11.0

**Comment by gnab** [comment]
Setting `smartypants: true` when creating the slideshow has no effect as this is not a known configuration option to remark. I'm planning move over to CommonMark, so Marked-specific features will then be unavailable unless re-implemented in remark anyways.
