### ISSUE TITLE
Uncaught SecurityError in Chrome 45

### ISSUE THREAD

**Issue by LPGhatguy** [gnab/remark#268]
My system was just updated to Chrome 45 this morning, and now reading presentations directly from my local disk results in the following error:

`Uncaught SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL 'file:///Users/luciengreathouse/Documents/projects/presentations/flexbox.html#1' cannot be created in a document with origin 'null'.`

I can serve them from a small local server (`python -m SimpleHTTPServer 8000`) and it'll function just fine, but this was surprising because I'm supposed to present today!

I'm using the latest version of Remark (as in the example in the readme) on OS X.

**Comment by jkubrynski** [comment]
Same on Linux

**Comment by jmaslibre** [comment]
@Dominik-K reported this on #222 : 
Quote:
> Commenting out the lines 3561-3564 in the out/remark.js
>  if (typeof window.history.replaceState === 'function') {
>   window.history.replaceState(undefined, undefined, hash);
>   }
>  else {
> and 3566 solved the problem. This lines are introduced with #143.

The corresponding discussion about this chrome change is in:
https://code.google.com/p/chromium/issues/detail?id=301210

**Comment by cwash** [comment]
Same behavior just cropped up recently for me as well.

Chrome Version 45.0.2454.85 (64-bit)

**Comment by gnab** [comment]
This has now been released in version 0.12.

**Comment by jmaslibre** [comment]
Thanks!
