### ISSUE TITLE
Demo slideshow should demonstrate anchors.

### ISSUE THREAD

**Issue by martinhbramwell** [gnab/remark#271]
Hi.  I am trying without success to understand how to link from one slide to another using the name of the slide, as documented [in the wiki](https://github.com/gnab/remark/wiki/Markdown#name).

Could you add a slide to demonstrate that, please?

**Comment by gnab** [comment]
Here you go:

http://jsfiddle.net/6gdwkg5m/

**Comment by martinhbramwell** [comment]
Ah Okay!! 

So the wiki fell short!  Please approve [my edit](https://github.com/gnab/remark/wiki/Markdown#name)

**Comment by gnab** [comment]
You edit looks fine. I merged it with the existing bullet point for these kind of slide links, and just included the Markdown syntax example of creating a link.

**Comment by martinhbramwell** [comment]
Cool.  Glad to help, even if only a teeny bit.

I'm doing something with Remark that you might like ... [Meteor-CI-Tutorial](https://github.com/martinhbramwell/Meteor-CI-Tutorial).

Currently, it's specific to preparing a Meteor project for continuous integration.  However, I intend to make a skeleton version, called something like "Remarkable-Install-Tutorials", that anyone can use to document complicated installation/setup procedures.  Scattered throughout the shell scripts (```Step0*.sh```) are calls to ```explain()```.  ```explain()``` echoes markdown text to the command line user and pauses for instructions.  The script ```concatenate.sh``` collects the markdown text into a GitHub pages website ( [Meteor-CI-Tutorial](https://martinhbramwell.github.io/Meteor-CI-Tutorial/) ) with on or more Remark slide shows. It also uses annotations in the installation scripts to add features to the slides; hyper-links to the relevant section of code, for example.
