### ISSUE TITLE
cannot have more than one style for code

### ISSUE THREAD

**Issue by jberkus** [gnab/remark#273]
I have the following style to display code:

.explain3 {
    white-space: pre-line;
    font-family: 'Monospace';
    font-size: 32px;
    background-color: #000000;
    padding-left: 0.5em
}

However, I find that when it renders, that "pre-line" does me no good because the Remark.js engine has already stripped all of the whitespace out of the text.  If I mark it as code with ```, then the Remark.js code formatting steps in, and any distinct font sizing or colors in an outer style is ignored.

What all of this adds up to is that there doesn't seem to be any way to have 28pt code on slide 4, and have 36pt code on slide 5, no matter how much you want to.

Fixes/workarounds?

**Comment by jpetazzo** [comment]
I don't know if that will help you, but specifically for sample code size, I regularly nest triple-backticks within `.small[ ... ]` blocks, like [here](https://github.com/jpetazzo/orchestration-workshop/blob/0440d1ea8dc35f2cfb2295282165ef3d1b1ab6a9/www/htdocs/index.html#L1628).

**Comment by jberkus** [comment]
hmmm.  I tried something like that, but it didn't work for me; the code style overrode the outer style.  I think it's working for you because you use the default text size for the remark-code style, but I don't because I'm using a much bigger default text size.  However, that does give me some ideas, thanks.

**Comment by abelards** [comment]
This looks fixed for quite some time now, so I'm closing the issue.

Sadly, @jpetazzo's link doesn't work anymore so we can't see the example "in situ", but the idea is still here.

Cheers,

**Comment by jpetazzo** [comment]
Just in case someone stumbles upon this and looks for my example: it's [here](https://github.com/jpetazzo/container.training/blob/0440d1ea8dc35f2cfb2295282165ef3d1b1ab6a9/www/htdocs/index.html#L1628) (I renamed that repository a while ago).

Cheers!
