### ISSUE TITLE
JSX highlighting

### ISSUE THREAD

**Issue by tgoldenberg** [gnab/remark#274]
Just curious how I would highlight .jsx code? By following the code in the official sample, I can get HTML highlighted, but .jsx files have both JS code and HTML code. `<pre><code>` tags work for the JS, but not the HTML, and the ````xml` code works for HTML but not JS. Any suggestions? Thanks!

**Comment by gnab** [comment]
Sorry for the slow reply. remark uses [highlight.js](https://highlightjs.org/) for highlighting, and currently there doesn't seem to be any support for JSX, but I would be surprised if it is not added at some point. If you're up for it, you can also contribute with languages to highlight.js yourself.
