### ISSUE TITLE
Implement more language highlighting

### ISSUE THREAD

**Issue by LPGhatguy** [gnab/remark#275]
Why does Remark only ship with a subset of languages? Highlight.js has so much more to offer than the few bundled ones. Is there a way to quickly override the language list and provide a custom Highlight build?

I'm looking for Sass and Lua both, neither of which are support out of the box, but are in Highlight.js.

**Comment by nicholas-leonard** [comment]
+1 to this. I also need Lua.

**Comment by gnab** [comment]
All languages supported by Highlight.js 9.0.0 is now available in the recently released version 0.13.

**Comment by nicholas-leonard** [comment]
@gnab awesome! Thanks.
