### ISSUE TITLE
Line highlighting with "*" no longer works

### ISSUE THREAD

**Issue by rposbo** [gnab/remark#276]
See the demo site itself: http://remarkjs.com/#8

You'll just see the asterisk instead of the whole line being highlighted.

**Comment by gnab** [comment]
It has been disabled by default. Please see:

https://github.com/gnab/remark/wiki/Configuration#highlighting

**Comment by rposbo** [comment]
Ah thanks - so perhaps this issue should be to update the remarkjs.com website to have it enabled.

**Comment by gnab** [comment]
Good idea. Fixed now.
