### ISSUE TITLE
Warnings due to synchronous XHR request

### ISSUE THREAD

**Issue by ColinEberhardt** [gnab/remark#277]
Currently the library uses synchronous XHR which results in the following warning in the console:

> Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience.

While remark still functions just fine, I like using remark with interactive demos via the console, as a result the above warning is a bit off-putting for the audience!

**Comment by ivanoats** [comment]
I'd like to bump this issue, because it's not just warnings in the console. If you are using a CDN, when you redirect to the CDN link from the source URL there's a 302, and it breaks.  Are you interested in a PR to fix?

**Comment by gnab** [comment]
@ivanoats PRs are always welcome :)

**Comment by ivanoats** [comment]
Something like this? 
https://github.com/ivanoats/remark/commit/3ebfa5ea925c2ce6f8f1e83a831d694f2383466d 

Tests fail but maybe due to the test framework mocking -  FakeXMLHttpRequest has no onload event

**Comment by gnab** [comment]
Version 0.14.0 that fixes this issue has now been released.
