### ISSUE TITLE
configuration to use "# heading" as start of new slide

### ISSUE THREAD

**Issue by paven** [gnab/remark#279]
It would be nice if 

     # Heading

could be used as an optionallstart of new slide

maybee by injecting --- in before "# the heading"

**Comment by paven** [comment]
This is maybe not so important... but still nice

**Comment by gnab** [comment]
It's a nice little feature, easily achievable like your suggesting, by injecting `---`. There may be several issues with doing this on a general basis in remark, but I created a demo for doing it outside of remark:

https://jsfiddle.net/8ehm02zy/

**Comment by paven** [comment]
:+1:
