### ISSUE TITLE
Cannot set text color in template

### ISSUE THREAD

**Issue by moebiuseye** [gnab/remark#280]
It would be a good idea to be able to set the text color in a slide header. 

Would that be easily feasible?

**Comment by gnab** [comment]
You can use [content classes](https://github.com/gnab/remark/wiki/Markdown#content-classes) to apply a class setting text color for a specific slide header, like this:

https://jsfiddle.net/5dyx8hum/

Or you can simply have CSS setting the color for all header elements of your choice, like `h1` which corresponds to `# ...`.
