### ISSUE TITLE
Support blockquote elements

### ISSUE THREAD

**Issue by NorthIsUp** [gnab/remark#281]
it seems that blockquote elements are not treated the same as other markdown constructs like code blocks, etc.

My naive look expects a `remark-blockquote` class on blockquote elements, there may be other things missing too.

what do you think?

**Comment by gnab** [comment]
What exactly is it you are asking for?

Blockquotes (using standard Markdown e-mail syntax `> ...`) ends up as `<blockquote>...</blockquote>` HTML in the slideshow:

https://jsfiddle.net/56o8jn8w/

**Comment by abelards** [comment]
@NorthIsUp do you mean you want better blockquote? I'm closing this ticket since there's more discussion on the same topic here on issue 305: https://github.com/gnab/remark/issues/305
