### ISSUE TITLE
Remarkise css

### ISSUE THREAD

**Issue by paven** [gnab/remark#283]
Adding a css input field for custom css on Remarkise.

**Comment by gnab** [comment]
Remarkise is the work of @tripu, so maybe he is up for adding this feature. If not, pull requests are always welcome :)

**Comment by tripu** [comment]
Thanks for the suggestion, @paven!

@gnab, can you assign me to this one please, so that it appears on my list of pending issues&hellip;?

**Comment by tripu** [comment]
Not maintaining Remarkise any more.
