### ISSUE TITLE
How to specify syntax higlighting into .md file

### ISSUE THREAD

**Issue by csigueros** [gnab/remark#286]
I'm wondering how can I add highlighting properties inside the .md file, right now I'm only able to specify the language but none of the other properties.

I want to do something like this:

'''java, highlightStyle: idea
package com.yyy.zzz;
...

'''

Thanks.

**Comment by gnab** [comment]
You can set a highlight style per slideshow and override it per slide, but not per code block:

https://jsfiddle.net/7dx8fuxb/1/
