### ISSUE TITLE
How to concatenate content?

### ISSUE THREAD

**Issue by yitzhakbg** [gnab/remark#287]
I'm running remarkjs from within [hugo](https://github.com/spf13/hugo). The markdown file is processed through the sourceUrl parameter as follows:
```
 var slideshow = remark.create({
          highlightStyle: 'monokai',
          highlightLanguage: 'remark',
          highlightLines: true,
          sourceUrl: "/slides/{{ .Params.slidesfile }}"
        }) ;
```
where .Params.slidefile is the name of the file. What I need to do is concatenate content to the file prior to processing, something, say like a.md+b.md. Is there a way?

**Comment by lambdalisue** [comment]
I use followin skeleton to concatenate markdown. Remember that you need to use some simple server then

```html
<!DOCTYPE html>
<meta charset="utf-8">
<title>Laboratory meeting</title>
<link rel="stylesheet" href="css/base.css">
<link rel="stylesheet" href="css/slide.css">
<textarea id="source"></textarea>
<script src="js/remark.min.js"></script>
<script src="js/jquery-2.1.4.min.js"></script>
<script>
var slideshow;
$(function() {
  $.when(
    $.get('slides/00-begin.md'),
    $.get('slides/01-introduction.md'),
    $.get('slides/99-end.md')
  ).done(function() {
    var args = Array.prototype.slice.call(arguments);
    var contents = args.reduce(function(previousValue, currentValue) {
      return previousValue + currentValue[0] + "\n---\n";
    }, '');
    $('#source').html(contents);
    slideshow = remark.create({
      ratio: '16:9'
    });
  });
});
</script>
```

**Comment by gnab** [comment]
You could do as @lambdalisue suggests, or perhaps Hugo is capable of concatenating the content into a single Markdown file that can be handed over to remark. I am not familiar with Hugo, though, so unless you go with the suggested answer you'll have to do some more research on the capabilities of Hugo.
