### ISSUE TITLE
Code line highlighting not working

### ISSUE THREAD

**Issue by DavideMontersino** [gnab/remark#290]
using the asterisk as in the example code to highlight a line does not work: 
```ruby
def add(a,b)
*  a + b
end

Notice how there is no return statement.
```

Dis something change in highlight.js maybe?

**Comment by gnab** [comment]
As of version [0.11](https://github.com/gnab/remark/blob/develop/HISTORY.md#011), including #192, highlighting of lines with a leading asterix was disabled by default, and must now be enabled explicitly, as pointed out in #251.
