### ISSUE TITLE
How to prevent some images to resize?

### ISSUE THREAD

**Issue by christophdebaene** [gnab/remark#293]
I would like to prevent some images to resize inside my presentation due to the `remark-slide-scaler`. Like for example the following gif image isn't as clear in the presentation due to the resize. 

**Original**

![](http://www.enterpriseintegrationpatterns.com/img/SharedDatabaseIntegration.gif)

**In presentation**
![sample](https://cloud.githubusercontent.com/assets/642207/12568931/5bc70080-c3ca-11e5-89e7-b4364794c3bb.PNG)

Is there a way like for example through css to keep the original size of the image no matter what?

**Comment by gnab** [comment]
No, that is not possible with the current implementation. The whole slide and everything in it is scaled to make you slide fill the screen regardless of screen resolution.

I would really recommend that you use vector graphics, like SVG, that will stay crisp at any scale. You can for instance use [draw.io](https://www.draw.io/) to easily create diagrams like the one in your example.

**Comment by christophdebaene** [comment]
Ok, thank you for the feedback
