### ISSUE TITLE
Selectively Remove Slide Count

### ISSUE THREAD

**Issue by ElizabethAB** [gnab/remark#298]
I'm building out a transition slide style and am wondering if there is a way to selectively remove slide counts from the bottom right-hand corner?

**Comment by gnab** [comment]
Yes, this is easily accomplished using the [class](https://github.com/gnab/remark/wiki/Markdown#class) slide property to add a CSS class to the slide, which in turn can be used to hide the per-slide `.remark-slide-number` DOM element for that specific slide, like in this demo:

https://jsfiddle.net/ox30embh/

**Comment by ElizabethAB** [comment]
Thank you!
