### ISSUE TITLE
Separate HTML and Markdown

### ISSUE THREAD

**Issue by kerim** [gnab/remark#30]
I'm wondering if there is someway to separate the HTML file from the Markdown text? Ideally I'd like to do it with something other than a PHP include (the only way I know how) since I'd using this on a USB drive and can't be sure that PHP is installed on whatever computer I might be using. Is there someway to do this in Javascript? 

A bit more explanation: I found Remark because I'm using FoldingText, a Markdown based outlining app for OS X. My goal would be to be able to quickly and easy edit presentations entirely within FoldingText. For this reason it would be nice to have the HTML file separate from the MD/TXT file. 

Thanks!

**Comment by paven** [comment]
<script>
    	var slideshow = remark.create({
    		sourceUrl: 'outline.md'
    	});
     </script>

**Comment by kerim** [comment]
Thanks @paven that works great. I'm running it on gh-pages now and it seems fine. It did take a litlte trial and error though. For those who need some guidance:

1. remove  `<textarea id="source"> ... </textarea>`
2. Use the code above in place of the existing code at the bottom: ` <script> var slideshow = remark.create(); </script>`

I was even able to move outline.md into an "includes" folder by using `includes/outline.md` however, I'm wondering if there is any way on gh-pages to generate a dynamic list of all the outlines in that folder and pick one of them from index.html?

**Comment by edbrannin** [comment]
@kerim This is less about Remark, but I think you could probably make a Jekyll template that renders a JSON list of posts.
