### ISSUE TITLE
Internet Explorer restricted this website from running scripts or activex control

### ISSUE THREAD

**Issue by iswardasa** [gnab/remark#300]

**Comment by iswardasa** [comment]
- ie 11
- windows 7
- running Norton Security

is this normal behavior of remark to require user authorization to be executed upon page load?

**Comment by iswardasa** [comment]
curiosity is there about the functionality of remark, because I am looking for a slideshow solution that does not require user permissions to be able view the slideshow..   scripts from other websites work just fine on this same browser/os combination.

**Comment by iswardasa** [comment]
admittedly, this windows installation that I have access to right now is very restrictive.  also, admittedly, I know very little about how remark works.  maybe I am overlooking something.

**Comment by gnab** [comment]
You are the only one I can recall ever having brought this issue up. I'm guessing your system settings may be causing this.

**Comment by iswardasa** [comment]
that is probably true.  i  was running remark on one of the most locked down machines windows machines i've ever seen.  it is good to get your feedback.  the browser simply asked for permission to run remark, which may not be a very acceptable side-effect considering that this issue is likely to be extremely rare.
