### ISSUE TITLE
Provide remarkjs.com example in .md?

### ISSUE THREAD

**Issue by fladd** [gnab/remark#302]
It would be great to have the example document on remarkjs.com available as a .md. And/or the CSS stylesheet used.

**Comment by iliocatallo** [comment]
+1

**Comment by carlwgeorge** [comment]
The source of the page has the markdown and CSS embedded in it.

**Comment by malikoth** [comment]
First of all, it is available if you switch to the `gh-pages` branch of this repo.  Second, I was wondering if any of you would care to chime in on #345 ?

**Comment by abelards** [comment]
On a remark slide, the best is to "view source" from your browser, or saving the HTML to open it with your preferred editor. Let me know if I should be more specific in the wiki, but for now I'll close the issue.
