### ISSUE TITLE
Line highlighting broken between 0.10.0 and 0.11.0

### ISSUE THREAD

**Issue by ashleywalsh** [gnab/remark#303]
Line highlighting stopped working in 0.11.0.  Using the example case:

```
    ```ruby
    def add(a,b)
    *  a + b
    end

    Notice how there is no return statement.
    ```
```

Highlighting stopped working when I changed the script URL from https://gnab.github.io/remark/downloads/remark-0.10.0.min.js to https://gnab.github.io/remark/downloads/remark-0.11.0.min.js

**Comment by ashleywalsh** [comment]
Oops, just found #192.  I guess the wiki need to be updated instead to point this out.
([Markdown#line-highlighting](https://github.com/gnab/remark/wiki/Markdown#line-highlighting))

Oh dear, also just found #251 and #290.

**Comment by gnab** [comment]
Wiki has been updated.
