### ISSUE TITLE
Highlighting not working after upgrade

### ISSUE THREAD

**Issue by Confusion** [gnab/remark#311]
If I switch from `remark-0.11.0` to `remark-latest`, the Ruby code blocks in my presentation are no longer highlighted (nor are they in a separate 'box'). From the HISTORY.md, README, wiki and commits it is unclear to me what I need to change in my presentation to re-enable highlighting.

I see that in the example presentation, it's no longer simply
```html
    <script src="http://gnab.github.io/remark/downloads/remark-0.11.0.min.js" type="text/javascript">
    </script>
    <script type="text/javascript">
      var slideshow = remark.create({
        highlightStyle: 'solarized_dark'
      });
    </script>
```

Extra scripts are loaded and a variable is being set. I'm unclear from what URL I can load `ruby.language.js` and whether I indeed need to copy what is in the example presentation.

**Comment by eljefe6a** [comment]
You have to add `highlightLines: true`. I wished that was the default.

**Comment by gnab** [comment]
As pointed out by @eljefe6a, you need to set `highlightLines: true`. This was set to `false` by default as it causes code blocks in various languages, such as C++ (having lines starting with `*`), to be rendered incorrectly.
