### ISSUE TITLE
Fit / Fill text in slide

### ISSUE THREAD

**Issue by alperyilmaz** [gnab/remark#316]
The fit/fill text property in [DeckSet](http://www.decksetapp.com/) ([sample](http://www.decksetapp.com/cheatsheet/#headings)) and [Spectacle](http://stack.formidable.com/spectacle) (sample [slide3](http://stack.formidable.com/spectacle/#/3) and [slide7](http://stack.formidable.com/spectacle/#/7)) is a nice touch for having beautiful slides. I was trying to integrate fit/fill text property into remark. I decided to try [BigText.js](https://github.com/zachleat/BigText) library (another alternative is [FitText](http://fittextjs.com/)). Currently I have the following lines in HTML:

``` html
<script src="https://gnab.github.io/remark/downloads/remark-latest.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="js/bigtext.js"></script>
<script>
var slideshow = remark.create({

// ratio, navigation,slideNumberFormat,countIncrementalSlides,highlightStyle,sourceUrl variables are set here

}); 
</script>
<script>
// Only BigText on “new-ish” browsers
if( 'querySelectorAll' in document ) {
$('.bigtext').bigtext();
}
</script>
```

When I view the presentation, I had to refresh the slide to see the effect. (same problem with mermaid was described in issue #315 

When I refresh, I see that BigText.js works as shown before:

![BigText.js sample](https://cloud.githubusercontent.com/assets/410615/14233366/099c3ca4-f9cf-11e5-8ee3-ca3323fa03d4.png)

My questions are;
1. What is the best way to integrate an external js library into remark? (do we need to trigger slide events?)
2. Is it possible to achieve fit/fill text effect by css only?

**Comment by dastrobu** [comment]
I have the same problem with [mermaid](http://knsv.github.io/mermaid/) and [flot.](http://www.flotcharts.org). At least some *slide loaded* to hook on would be nice. I currently did not find any other solution except reloading the page after switching slides, which is not really an option.

**Comment by jenokarthic** [comment]
I had the similar issue and find the solution.   Following code receives **slideshow** callback from remarkjs and recreate the bigtext content.

```
<script>
slideshow.on('afterShowSlide', function (slide) {
if( 'querySelectorAll' in document ) {
$('.bigtext').bigtext();
}
</script>
```

**Comment by dastrobu** [comment]
@jenokarthic tip works also great with [flot](http://www.flotcharts.org) and solves the issue. For completeness, the plot must be called via: 

    slideshow.on('afterShowSlide', function(slide){
        $.plot("myPlotSelector", [...]);
    });

**Comment by abelards** [comment]
Thanks everyone, now it's in the wiki!
https://github.com/gnab/remark/wiki/HTML-CSS-JS-samples
