### ISSUE TITLE
background-image

### ISSUE THREAD

**Issue by mpusz** [gnab/remark#317]
Please do not add any size or position info to the background-image via Java Script (even if the image is larger) as described here https://github.com/gnab/remark/wiki/Markdown#background-image. In such case user cannot control those properties via CSS files and for example use 'cover' for background-size.

**Comment by codergolem** [comment]
It seems that a solution for this was implemented with d0332282a6f9f5be7f41c424b8055af6f6e93d9. But it does not work for me

**Comment by ogrisel** [comment]
It does work if you build and use `remark.min.js` from the develop branch where d0332282a6f9f5be7f41c424b8055af6f6e93d92 has been pushed (not part of the latest release at this time).

```
git clone https://github.com/gnab/remark
cd remark
make
```

then use `out/remark.min.js` as done in `boilerplate-local.js`.

If you don't have a recent enough version of node / npm installed on your machine you can run `make` using the official node docker container which is up to date:

```
git clone https://github.com/gnab/remark
cd remark
docker run --rm -v $PWD:/io -w /io node make
```

**Comment by gnab** [comment]
Version 0.14.0 containing the fix by @jbeda has now been released.
