### ISSUE TITLE
Auto-render with Katex

### ISSUE THREAD

**Issue by goessner** [gnab/remark#319]
Just to let you know ...

on [wiki page](https://github.com/gnab/remark/wiki/LaTeX-Using-KaTeX)  for both delimiters `$` and `$$` working with Katex you need to code them in correct order:

```
 renderMathInElement(document.body, {delimiters: [
           {left: "$$", right: "$$", display: true},
           {left: "$", right: "$", display: false}
      ]});
```

**Comment by anaderi** [comment]
updated wiki page (also one have to include katex.min.css)

**Comment by abelards** [comment]
I'm closing the issue, since it looks fixed or documented.
