### ISSUE TITLE
Create HTML presentation from Markdown file

### ISSUE THREAD

**Issue by munrocape** [gnab/remark#320]
Is it possible to have remark (pre/ap)pend the required header/footer for the HTML file? Perhaps also passing in a .css file if additional styling is required. Something like

```
> ls -1
slides.md 
slides.css
> remark generate slides.md --css slides.css
Created slides.html
> ls -1
slides.md
slides.css
slides.html
```

Alternatively, maybe the CSS file could be included in the frontmatter.

I have just found remark and think this would fit into my workflow. If this isn't supported, I would be interested to find out why and if developing some simple package would be helpful.

**Comment by scotthewitt** [comment]
Could you not use a static site generator like Jekyll to do this?

**Comment by abelards** [comment]
It looks like any of these static generators would work, remark-compose (python/jinja2) being dedicated to remark, and jekyll (ruby/liquid) or hugo (golang) should work too:
https://github.com/gnab/remark/wiki/Static-Generators
