### ISSUE TITLE
Autoplay video when slide opens

### ISSUE THREAD

**Issue by williamsmj** [gnab/remark#322]
I'm currently embedding webm videos with code like

``` html
<video loop autoplay controls>
    <source src="video.webm">
</video>
```

These videos begin autoplaying when the presentation loads. Is there any way to have them begin autoplaying when the _slide_ loads?

This is [possible in reveal](https://github.com/hakimel/reveal.js/#embedded-media) but I couldn't find similar syntax in the remark documentation.

**Comment by Unode** [comment]
[Possible workaround](http://victorfont.com/pause-html5-video-when-out-of-viewport/)

**Comment by nolanlawson** [comment]
I'm using the following code, which autoplays all videos from start time 0 when the slide is shown. Works well for me!

```js
  var slideElements

  function getElementForSlide(slide) {
    slideElements = slideElements || document.querySelectorAll('.remark-slide')
    return slideElements[slide.getSlideIndex()]
  }

  slideshow.on('showSlide', function (slide) {
    Array.from(getElementForSlide(slide).querySelectorAll('video')).forEach(function (vid) {
      vid.loop = true
      vid.currentTime = 0
      vid.play()
    })
  })

  slideshow.on('hideSlide', function (slide) {
    Array.from(getElementForSlide(slide).querySelectorAll('video')).forEach(function (vid) {
      vid.pause()
    })
  })
```

**Comment by Unode** [comment]
Thanks, this is much lighter than the workaround I linked.

This should also be applicable to `<audio>` tags.
As far as I know they use the same attributes (`.loop`, `.currentTime`, `.play`, `.pause`, ... ).

**Comment by Nerdyneer** [comment]
@nolanlawson 
Where should I add this code?

**Comment by abelards** [comment]
The question is answered on both links so I'm closing the issue.

**Comment by freder** [comment]
slightly improved version of @nolanlawson's solution:
- data attribute as autoplay flag
- mute videos in presenter mode

```js
let slideElements;
const body = document.body;
function getElementForSlide(slide) {
	slideElements = slideElements || document.querySelectorAll('.remark-slide');
	return slideElements[slide.getSlideIndex()];
}
slideshow.on('showSlide', (slide) => {
	getElementForSlide(slide).querySelectorAll('video').forEach((vid) => {
		if (body.classList.contains('remark-presenter-mode')) {
			vid.muted = true;
		}
		if (vid.attributes['data-autoplay'].value === 'true') {
			vid.play();
		}
	});
});
slideshow.on('hideSlide', (slide) => {
	getElementForSlide(slide).querySelectorAll('video').forEach((vid) => {
		vid.pause();
	});
});
```

**Comment by tjex** [comment]
works great 👆
just be sure to not keep `autoplay="false"` in any video elements, otherwise it breaks the functionality of the script. 

e.g. don't do this: `<video width="100%" autoplay="false"  controls>`

**Comment by tjex** [comment]
> @nolanlawson Where should I add this code?

anywhere between `<script></script>` tags in your main presentation's html file i.e `index.html`

```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Remark</title>
    <link rel="stylesheet" type="text/css" href="./reflex.css" />
    <script>
      <!-- code goes here -->
    </script>
  </head>
  <body>
    <textarea id="source">
```
