### ISSUE TITLE
Hidden Comments

### ISSUE THREAD

**Issue by scotthewitt** [gnab/remark#325]
Hidden Comments

Hi often when i am making a presentation I like to have extra notes for myself which I don't want displayed in the notes at all.

I know that comments in markdown is a problem but perhaps something could be implemented in remark?

Am thinking an extra division within ??? that prevents text being displayed marking a possible slide be;

> ---
> # Slide
> 
> ???
> Note about the slide for people to read
> 
> Some extra separator like but not ---   or ??? here
> 
> Super top secret notes not displayed

**Comment by stiemannkj1** [comment]
@scotthewitt, if you are talking about in-slide notes, I have a simple solution: use the [content class feature of remark](https://github.com/gnab/remark/wiki/Markdown#content-classes):

```
<style type="text/css">
.invisible-ink {
    display: none;
}

.remark-container.remark-presenter-mode .invisible-ink {
    display: inline;
    color: red;
}
<style>

<!-- your code here -->

<textarea id="source">

# My Slide

Here's some text. .invisible-ink[Here's some text that only shows up in presenter mode.]

</textarea>
```

**Comment by scotthewitt** [comment]
Obvious idea awesome thanks

**Comment by DustinWehr** [comment]
This worked well for me. Maybe it should be in the FAQ?

**Comment by abelards** [comment]
Documented here, thanks!
https://github.com/gnab/remark/wiki/HTML-CSS-JS-samples
