### ISSUE TITLE
Background-repeat behaviour

### ISSUE THREAD

**Issue by remimarenco** [gnab/remark#327]
Hi,

I have some troubles using background-repeat in my MarkDown.

As somebody was raising an issue [here](https://github.com/gnab/remark/issues/211), it doesn't seem to work for me too. In your example @gnab , it shows "no-repeat" as raw text.

On my side, if I set this in my .md:

```
background-image: url(images/app_architecture/job_management.png)
background-position: center;
background-repeat: no-repeat;
background-size: contain;
```

I have this as output in my *.html:

``` html
<div class="remark-slide-content inverse center middle hljs-default"
style="background-image: url(&quot;images/app_architecture/job_management.png&quot;);
background-size: 908px 246.495px;
background-position: 50% 217.253px;">
<div class="remark-slide-number">22 / 85</div>
</div>
```

Am I misusing the feature?

**Comment by gnab** [comment]
The `.remark-slide-content` CSS class defined `background-repeat: no-repeat`, so the background should never be repeated. In my example I simply wrote "no-repeat" as raw text on the slide, it wasn't supposed to have any special meaning for the slideshow as such.

The updated demo (https://jsfiddle.net/qytg78tp/1/) still shows a single background image in Chrome on my machine:

![image](https://cloud.githubusercontent.com/assets/158686/18017921/3bb4a236-6bd4-11e6-9023-09339fa5aeb3.png)

If I tweak the CSS in developer tools to _disable_ the default `no-repeat`, you see the background repeated:

![image](https://cloud.githubusercontent.com/assets/158686/18017975/8aab60b4-6bd4-11e6-810a-dc92cf8c47a4.png)

If you see different behaviour on your side, what browser are you on?

**Comment by remimarenco** [comment]
Thank you @gnab for taking the time to investigate. It is quite far now, and I am not doing this project anymore, I guess this is not an issue if you don't have the same behavior! (I am on Chrome to answer your question).

Thanks again for your answer and the work!
