### ISSUE TITLE
Upgrade to new highlight.js with Elm 0.17

### ISSUE THREAD

**Issue by ulsa** [gnab/remark#330]
Just a heads up on an upcoming release of highlight.js with [support for Elm 0.17](https://github.com/isagalaev/highlight.js/pull/1172).

**Comment by ulsa** [comment]
They just released [highlight.js 9.4.0](https://github.com/isagalaev/highlight.js/releases/tag/9.4.0).

**Comment by gnab** [comment]
Version 0.14.0 released just minutes ago bundles Highlight.js 9.6.0 :)
