### ISSUE TITLE
Widget for iFrame, Widget for Source Code Display

### ISSUE THREAD

**Issue by ghost** [gnab/remark#332]
As I give a presentation, I'd like to have to navigate around my system as little as possible. I'd like to be able to embed an iFrame in one of my slides to enter a demo my web app - I'd also like to be able to show full-slide scrollable source listings such as CodeMirror and not just snippets.

I'll be looking into adding this stuff later today. Feel free to let me know if this already exists. If it doesn't, I think these capabilities would be nice to have as a plugin.

**Comment by abelards** [comment]
I think a normal iframe would do the trick.
Since the user was deleted, I'm closing this issue.
