### ISSUE TITLE
Ordered lists

### ISSUE THREAD

**Issue by Vebryn** [gnab/remark#334]
Hi,

I'm wandering if it's possible to start at a specific number with ordered lists ?

I don't think if its possible. A feature request ? :)

Best regards.

**Comment by arogozhnikov** [comment]
This can't be down in markdown, unless going down to html

http://stackoverflow.com/questions/15078393/begin-ordered-list-from-0-in-markdown

**Comment by Vebryn** [comment]
Thank you, not so easy!
