### ISSUE TITLE
Footnotes & "--" feature

### ISSUE THREAD

**Issue by Vebryn** [gnab/remark#335]
Hi,

I notice that ??? footnotes and "--" dynamic slides are not compatible. For now, I duplicate my slides.

Exemple

```
# title
- item 1
???
- footnotes 1
--

- item 2
???
- footnotes 2
```

Best regards.

**Comment by Unode** [comment]
Isn't this fixed already? It works for me.

**Comment by gnab** [comment]
@Vebryn Currently "footnotes 1" is displayed initially, and when the incremental slide is applied, showing "item 2", "footnotes 2" is also shown in the notes section. So both the contents and the notes are incrementally applied. 

Live demo of your example: https://jsfiddle.net/5v4uf2ap/

**Comment by Vebryn** [comment]
I made a mistake with my explanation. It concerns only 2nd level of a list.

```
# title
- item 1

???
- footnotes 1

--

 - sub-item 1

???
- footnotes 2
```

**Comment by tripu** [comment]
WFM.

**Comment by utdrmac** [comment]
@Vebryn Can you close this issue if all is good?
