### ISSUE TITLE
Generate one-page document instead of displaying page by page?

### ISSUE THREAD

**Issue by robert-dodier** [gnab/remark#338]
I wonder if there's any way to tell Remark to generate a one-page HTML document. So a reader could see the entire document without going page by page.

The problem I've bumped into is that I'm trying to use htmlpreview.github.io to display a presentation I have on Github. However, when I try that, it shows just the title page, and the arrow keys don't work for navigation. I can go to a specific page by appending #nn to the URL (dunno if that's relevant).

For the record, the URL is: http://htmlpreview.github.io/?https://github.com/robert-dodier/spark-incremental/blob/master/spark-incremental.html

I am guessing that htmlpreview. is not allowing Javascript to run; does that seem plausible? If so, I wonder how to work around that. If could display the entire document at once, even without rendering the math formulas, that would be enough for me.

Thanks in advance for any light you can shed on this problem.

**Comment by sinedied** [comment]
If you fiddle with the css, It should definitely be possible, for example by displaying `.remark-container` elements side by side.

When I use you link, I have no issues navigating by keys, so it's not a JS issue.

**Comment by abelards** [comment]
I think this is what the "print" feature does and I think it's been done since 2016. Can we close the issue?

**Comment by robert-dodier** [comment]
OK by me to close it. I haven't tried that idea but I don't need to solve this problem anymore so we can leave it at that. Thanks for the suggestions, I appreciate your help.
