### ISSUE TITLE
Redirection to HTTP

### ISSUE THREAD

**Issue by herrjemand** [gnab/remark#340]
In the example, script location is at **https**://gnab.github.io/remark/downloads/remark-latest.min.js, but because it is at custom domain, it **http**://remarkjs.com/downloads/remark-latest.min.js

Possible solutions:

 - User raw https://raw.githubusercontent.com/gnab/remark/gh-pages/downloads/remark-latest.min.js
 - Add HTTPS support to remarkjs.com

**Comment by herrjemand** [comment]
Ok. Fuck me. https://raw.githubusercontent.com/gnab/remark/gh-pages/downloads/remark-latest.min.js that does not work, because of git's incorrect mime for script. 
How about rawgit?
https://rawgit.com/gnab/remark/gh-pages/downloads/remark-latest.min.js

**Comment by gnab** [comment]
I added forced HTTPS for remarkjs.com now, so this should no longer be a problem.

**Comment by teppeis** [comment]
@gnab Not fixed.

```console
$ curl 'https://gnab.github.io/remark/downloads/remark-latest.min.js' -v
*   Trying 151.101.100.133...
* Connected to gnab.github.io (151.101.100.133) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: www.github.com
* Server certificate: DigiCert SHA2 High Assurance Server CA
* Server certificate: DigiCert High Assurance EV Root CA
> GET /remark/downloads/remark-latest.min.js HTTP/1.1
> Host: gnab.github.io
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Server: GitHub.com
< Content-Type: text/html
< Location: http://remarkjs.com/downloads/remark-latest.min.js
< X-GitHub-Request-Id: 67F5E01B:26A05:8E0715C:57E88565
< Content-Length: 178
< Accept-Ranges: bytes
< Date: Mon, 26 Sep 2016 02:21:33 GMT
< Via: 1.1 varnish
< Age: 200
< Connection: keep-alive
< X-Served-By: cache-itm7421-ITM
< X-Cache: HIT
< X-Cache-Hits: 1
< Vary: Accept-Encoding
< X-Fastly-Request-ID: 7abd892831cfc5f283b738bef2c53bac72b9407e
< 
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
* Connection #0 to host gnab.github.io left intact
```

So the mixed-content is blocked by Chrome.
Can I use `https://remarkjs.com/downloads/remark-latest.min.js`
Can you fix HTML examples in this repo and README?

**Comment by herrjemand** [comment]
@gnab Somehow 301 redirects to HTTP and not HTTPS( Location: http://remarkjs.com/downloads/remark-latest.min.js)
 
@teppeis just use https://remarkjs.com/downloads/remark-latest.min.js
