### ISSUE TITLE
Switching to presenter mode but not getting a slideshow view to share with people

### ISSUE THREAD

**Issue by ayushgoel** [gnab/remark#341]
> Presenter mode, with cloned slideshow view

When I switch to presenter mode (press `p`), no cloned slideshow view appears. The existing window itself goes into presenter mode (with the notes and timer). Am I missing something?

**Comment by gnab** [comment]
Yes, you simply need to first press C to create the cloned view, and then press P in the original window to bring that one into presenters mode. Then, the cloned view you created will follow the navigation of the original one.

**Comment by gnab** [comment]
It's documented over three slides in the "official" remark slideshow, referenced in the README:

http://remarkjs.com/#14

I think it should go in the wiki alongside all the other info, probably under "Presenting" section that mentions the presenter mode and the timers and all that stuff.
