### ISSUE TITLE
Problems with printing (Str-P)

### ISSUE THREAD

**Issue by gerihu** [gnab/remark#342]
Hi,
thanks for this great piece of software. I have been using remark.js happily for a couple of slides but ran into a problem when I had to provide PDFs of my slides.

Browser: recent chromium 50.0.2661.94 (same problem in chrome).

Description: When browser is in a rather full screen size window (appr. 1600x1000 px) the rendered print (through Str-P) looks like linked image below with broad borders to the right and bottom.

http://www.filedropper.com/screenshot20160612093108

If I significantly reduce the window size of the browser the borders disappear but the images shift far down over the edge

http://www.filedropper.com/screenshot20160612093838

Styles are  unchanged from the remark.js intro slides.

Slide code is this:
```
---
## Boot from ISO image

If you own the image, no need to be root!

`qemu-kvm -m 512M -cdrom sysresccd.iso` 

<img src="qemu_rescuecd.png" alt="qemu screenshot" width="66%"/>
---
```
The size of the image is 640x503

**Comment by szpak** [comment]
There is a related issue #50 (unfortunately closed  although export with Chrome usually does not work as expected, espiecially for 16:9). You may be also interested in #313.

**Comment by Leryan** [comment]
In issue #50, mpusz came with a solution: a dedicated CSS hack that worked for me under Chromium 52.

**Comment by gnab** [comment]
Printing issues are a never ending story, especially since the browser support changes from one version to the next. Please give DeckTape a go, as mentioned [here](https://github.com/gnab/remark#printing).
