### ISSUE TITLE
Java Generics Issue

### ISSUE THREAD

**Issue by eljefe6a** [gnab/remark#348]
There is an issue where using several Java generics at once causes Remark to really slow down. I've created a repeatable code snippet:
```
<!DOCTYPE html>
<html>
  <head>
    <title>Title</title>
    <meta charset="utf-8">
    <style>
      @import url(https://fonts.googleapis.com/css?family=Yanone+Kaffeesatz);
      @import url(https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic);
      @import url(https://fonts.googleapis.com/css?family=Ubuntu+Mono:400,700,400italic);

      body { font-family: 'Droid Serif'; }
      h1, h2, h3 {
        font-family: 'Yanone Kaffeesatz';
        font-weight: normal;
      }
      .remark-code, .remark-inline-code { font-family: 'Ubuntu Mono'; }
    </style>
  </head>
  <body>
    <textarea id="source">

class: center, middle

\`\`\`java
*   Mapper<LongWritable, Text, Text, IntWritable> {

\`\`\`

    </textarea>
    <script src="https://gnab.github.io/remark/downloads/remark-latest.min.js">
    </script>
    <script>
      var slideshow = remark.create();
    </script>
  </body>
</html>
```

This will render after 5-10 seconds on my machine.

If you change the generics to:
```
*   Mapper<LongWritable> {
```

it will render in milliseconds. I think this is a bug in highlight.js. This issue doesn't happen with Remark 0.12, but it starts happening in 0.13. The release notes say the version of highlight.js is bumped.

**Comment by eljefe6a** [comment]
Confirmed that highlight.js 9.0 has this bug and highlight.js 9.5 doesn't have the issue. @gnab can we get a new release with 9.5?

**Comment by jypma** [comment]
In the meantime, what would be the steps to upgrade `highlighter.js` locally, so I can try to build a version myself?

**Comment by jypma** [comment]
Workaround: replace the comma with "，" (`\uFF0C`) or your own favourite unicode replacement. Makes copy/pasting code rather nasty though :-)

**Comment by gnab** [comment]
Version 0.14.0 containing upgrade to Highlight.js 9.6.0 has now been released.

**Comment by eljefe6a** [comment]
Version 0.14.0 was removed shortly after you closed this. Is it going to be released?

**Comment by gnab** [comment]
Yes, I pulled it back to fix something that went wrong, but now it has been released again.
