### ISSUE TITLE
Slide Properties Not Functional

### ISSUE THREAD

**Issue by IWriteThings** [gnab/remark#350]
My slide looks like the below.

```
name: agenda
class: center, middle

# Title Page

The name is {{name}}
```
When I display the slide show it looks like the attached image.
<img width="1382" alt="screen shot 2016-07-06 at 09 49 22" src="https://cloud.githubusercontent.com/assets/11728899/16626706/f64a2628-435e-11e6-96f2-7094a9bde1d6.png">

Is there some kind of preface that I need for the slide to know that the content I am adding has the properties and to interpret them correctly?

**Comment by gnab** [comment]
Do you have a `--` slide separator?

Demo: http://codepen.io/anon/pen/xOzjwk

**Comment by IWriteThings** [comment]
I do not have a -- slide separator.

**Comment by IWriteThings** [comment]
I was able to fix my issue by doing the following.

```
<textarea id="source">
<?php
	include_once( 'index.md' );
	include_once( 'next_slide.md' );
?>
</textarea>
```

I moved my markdown into includes using php and added the textarea around that. It now works. I am going to close this since I resolved my issue.
