### ISSUE TITLE
Availability on npm

### ISSUE THREAD

**Issue by jugglinmike** [gnab/remark#356]
Is this module available on npm? Judging from the `package.json` file, [it looks as though it was once published there as "remark"](https://github.com/gnab/remark/blob/4c9a86fcd91c430e93c5daba77b48caa29ba08e4/package.json#L2), but [that name is currently in use by another project](https://www.npmjs.com/package/remark).

**Comment by gnab** [comment]
No, but it is available via bower. So you can do `npm install -g bower && bower install remark`.

**Comment by jugglinmike** [comment]
That solution (globally installing a second package manager) is somewhat
onerous for many use cases because it involves an additional command in the
"traditional" installation process. Consumers who are creating application will
have to document that separately and burden their contributors (who often
require administrative privileges to install packages globally). As for
consumers who are creating utilities, I'm not sure that is a viable alternative
at all.

For anyone coming across this issue later on: you should be able to avoid many
of these problems by installing Bower locally--this blog post has details:

https://bocoup.com/weblog/a-facade-for-tooling-with-npm-scripts

That said, it's very inefficient to install all of Bower in order to consumer
another library! Since Remark is already following SemVer and regularly
publishing to Bower, synchronizing releases with npm should be relatively
straightforward. It'd be much appreciated!

Anyway, thanks for the excellent tool :)
