### ISSUE TITLE
[SOLVED] Properties used as variables expand incorrect when in style class inside a page template

### ISSUE THREAD

**Issue by tbfe-de** [gnab/remark#357]
Note: this issue has been solved!

A fix is available (see lines below), but not yet merged into the repository.

I also conserve the history (problem report and analysis) in this issue.

---
## The Solution (see also Analysis following)

JavaScript Gurus will probably be able to do this much better, but the change to the code below solves the problem described when this issue was opened (and hence confirms my analysis).

```
function inheritContent (slide, template) { <--- existing function that needs to be changed
  var expandedVariables;

    slide.properties.content = slide.content.slice();
  //slide.content = template.content.slice();
    deepCopyContent(slide, template.content);
    ...
    ...
}

function deepCopyContent(target, content) {  // <--- new helper (can probably be improved)
  var i;

  target.content = new Array();
  for (i = 0; i < content.length; ++i) {
    if (typeof content[i] === 'string') {
      target.content.push(content[i]);
    }
    else {
      target.content.push({
        block: content[i].block,
        class: content[i].class,
      });
      deepCopyContent(target.content[target.content.length-1], content[i].content);
    }
  }
}
```

---
## Analysis (preceding Solution in time)

After spending some time in the JavaScript Debugger I think the problem might be that for the `content` (Array) in a Slide there is only a shallow copy, leading to an aliasing problem if the content is not a string but a Content Class.

I have not enough knowledge of the Remark code and the JavaScript language to be able to fix this myself, but maybe in the function that "inherits" from a page template there should be some deep(er) copy mechanism used instead of `… .slice()`?

```
function inheritContent (slide, template) {
  var expandedVariables;

  slide.properties.content = slide.content.slice();
  slide.content = template.content.slice();  <--- might this may be the culprit?
```

---
## Problem Report (preceding Analysis in time)

After staying abstinent from updates of remarkjs for some years (as I found changes made during that time were not backward compatible and broke the large collection of presentations I have written with remarkjs) today I thought I'll bite the bullet and switch to `remark-latest`.

Most of the incompatibilities with the old version I could solve. But the problem demonstrated below seems to be a bug in logic when page properties are expanded **inside style classes used in page templates**:

```
layout: true
name: z

via template: name={{name}}

.x[class in template: name={{name}}]

---
name: first
template: z

in first page: name={{name}}

.x[class in first page: name={{name}}]

---
name: second
template: z

in second page: name={{name}}

.x[class in second page: name={{name}}]
```

First page looks correct:

```
via template: name=first

class in template: name=first

in first page: name=first

class in first page: name=first
```

Second page shows the problem:

```
via template: name=second <---- correct (template expanded from 2nd page)

class in template: name=first <--------- NOT correct

in second page: name=second

class in second page: name=second
```

The old code (from about two years ago, sorry, I don't know how to extract the version number from the minified JavaScript) does this correct:

```
via template: name=second

class in template: name=second

in second page: name=second

class in second page: name=second
```

**Comment by gnab** [comment]
Nice research! Your fix will be included in the next release :)
