### ISSUE TITLE
toLowerCase() missing for parsed-out reference links

### ISSUE THREAD

**Issue by tbfe-de** [gnab/remark#365]
Reference links "parsed-out" before the content of a slide is converted from Markdown to HTML via `marked` need to be turned into lower case (either in `lexer.js` or `parser.js`) as 'marked' seems to turn the content of `[Some Link]` also to lower case (`[some link]`) before it does the comparison.

This fixes the following problem:

```
… [Some Link] …

[Some Link]: target    <---- will not be found
[some link]: target  <--- unless in lower case
```

Anyway, after I solved this problem myself Issue #357 seems to be the sole reason why I'm still locked with the two-years old version of remark.js for my presentations ...

**Comment by gnab** [comment]
Also nice research. Fix scheduled for next release.
