### ISSUE TITLE
How to add support for languages not highlighted by default

### ISSUE THREAD

**Issue by lpil** [gnab/remark#368]
With highlight.js one can add a new language by linking the language file from their CDN.

https://github.com/isagalaev/highlight.js#getting-the-library

This does not seem to work with remark.js. How does one add a language not included by default?

Thanks,
Louis

**Comment by gnab** [comment]
You can access highlight.js via `remark.highlighter.engine`, so before you do `remark.create(...)` you can call [registerLanguage](http://highlightjs.readthedocs.io/en/latest/api.html#registerlanguage-name-language) using `remark.highlighter.engine.registerLanguage(...)`.

**Comment by lpil** [comment]
But what do I pass that? The language definitions for highlight js don't offer any value to add. They're just a script that immediately crashes because highlight.js isn't in scope.

**Comment by gnab** [comment]
You can simply expose `remark.highlighter.engine` via the global variable, `hjls`, that the langauge script expects to exist:

```html
<script src="remark.js"></script>
<script>
  var hljs = remark.highlighter.engine;
</script>
<script src="other-language.js"></script>
<script>
  var slideshow = remark.create();
</script>
```

**Comment by lpil** [comment]
I've tried this- it crashes still. I'll try and provide a stack trace when I have time

**Comment by gnab** [comment]
This demos it, with the custom `remark` language I've created for the remark web page: https://jsfiddle.net/cetuke6a/1/
