### ISSUE TITLE
Optional Properties

### ISSUE THREAD

**Issue by eljefe6a** [gnab/remark#371]
Is there a notation to have a property be optional? This would be a way to say "if this doesn't exist, don't leave the placeholder there."

For example, the property `{{ thispropertydoesntexist }}` will render as `{{ thispropertydoesntexist }}`. What I'd like to have is something like `{{ thispropertyMIGHTexist }}` and render as nothing ().

**Comment by tbfe-de** [comment]
If you work with page templates you could give it an empty default in the template.

An idea to provide even more flexibility is here #384.

**Comment by abelards** [comment]
Closing since we already have 1) a workaround and 2) another ticket where we can discuss the feature.
