### ISSUE TITLE
How to reduce space between top edge and slide title/header?

### ISSUE THREAD

**Issue by szpak** [gnab/remark#372]
I would like to reduce empty space between the top edge of a slide and a slide title/header (that one with `#`). Generated `h1` doesn't seem to have the top margin set. I could set it to negative value, however it impacts all `h1` elements and looks bad having two of them one-by-one.

I suspect to have a padding somewhere moving this tag down, however, looking at it with Firebug I don't see anything related (I'm not a CSS developer, probably I missed something).

How can I tweak CSS to have smaller space between the top edge and slide title/header?

**Comment by dcsan** [comment]
I'd like to know too! I don't see where the base CSS for this project is included?

**Comment by szpak** [comment]
@gnab Is it really impossible to do via CSS right now? If yes, maybe it would be good to handle a slide header in some specific way?

**Comment by gnab** [comment]
You can apply a couple of CSS rules:

```css
.remark-slide-content {
  padding-top: 0px;
}
.remark-slide-content > h1:first-of-type {
  margin-top: 0px;
}
```

First ones removed whitespace from the top of the slide, and the second removed the whitespace from to heading itself.

Live demo: https://jsfiddle.net/pnuhoquq/

**Comment by szpak** [comment]
Thanks for reply.

In general it works, but in the meantime I found what caused an extra space in my case - footer which adds extra `<p>` before a header. See https://jsfiddle.net/jnf8cjhn/

Maybe you have an idea how to deal with it?
