### ISSUE TITLE
inline code formatting?

### ISSUE THREAD

**Issue by gliptak** [gnab/remark#373]
I tried to use inline ```code formatting``` as follows:

---
discussing ```foo```
---
discussing ```bar```
---

but the two slides are displayed on a single screen. Removing back-ticks separates the slides (correctly).

Is there a different syntax to be used here?

Thanks

**Comment by tbfe-de** [comment]
Could you be a bit more specific? From the **formatted** example above it's hard to see what you mean.

In general inline code formatting like `this` or `that` uses **single** back-ticks.

Here is the formatted line once again, as it is written in Markdown:

```
In general inline code formatting like `this` or `that` uses **single** back-ticks.
```

I use it frequently and it works very well, but what I found is that *sometimes* an error on an earlier page (like inadvertently duplicating or forgetting to close a back-tick) has "surprising" effects like a large number of pages "vanishing" from the presentation.

Sometimes it can get really tricky to find the culprit, e.g. by "commenting-out" half of the presentation with HTML-comments and I would surely prefer to propose a less fragile parsing algorithm, but I did not manage do narrow down the problem enough to see its true origins.

**Comment by gliptak** [comment]
Thank you for the detailed pointers. I will switch to single back-tick for inline use.
