### ISSUE TITLE
Performance issue - High CPU usage on idle presentation

### ISSUE THREAD

**Issue by Unode** [gnab/remark#375]
Hi everyone,

While exploring some of the works linked from the main README file, [one in particular](http://www.jmlilly.net/talks/bigdata16.html) caught my attention for two reasons. First the nice animations and videos, second that my CPU fan was spinning faster than usual.

After some troubleshooting I realized that just by having this website open on Firefox, my CPU usage would spike to ~50%. I thought this could be related to #322 but I paused all videos and pretty much the same CPU was still being used.
Is this something that could be caused by remark.js or is it just Firefox having a hard time handling the content?

**Comment by gnab** [comment]
remark.js doesn't "do" anything besides hiding and showing slides, so when you are viewing a slide, remark is at rest, awaiting the next event to move forwards or backwards. I would say this is most likely due to Firefox and the contents of the slide, as you are suggesting.

**Comment by Unode** [comment]
Thanks for the feedback.

Still no clue why or what on the page causes it to spike the CPU like that but that belongs in another bugtracker.
