### ISSUE TITLE
Jekyll usage documentation is not working

### ISSUE THREAD

**Issue by cchantep** [gnab/remark#377]
The [Jekyll documentation](https://github.com/gnab/remark/wiki/Using-with-Jekyll) is not working, as it doesn't recognize the `---` as slide separator.

**Comment by seanlane** [comment]
I'm seeing the same issue as well.

**Comment by tom-jin** [comment]
You need to change the extention of your presentation markdown file to something other than `.md` like `.html` otherwise Jekyll is doing the rendering rather than remark.

**Comment by gnab** [comment]
Added the note to the wiki regarding the file extension. Closing this one.

**Comment by ratnanil** [comment]
> You need to change the extention of your presentation markdown file to something other than .md like .html otherwise Jekyll is doing the rendering rather than remark.

The wiki still says to:

> Create an .md file (the file in this example is default-presentation.md) containing your presentation.

Is it not updated or what is the best practice on working with jekyll? ~~I'm having issues setting the class of my first slide (independent of whether I use .md or .html).~~

Edit: I had an issue with my template.html, my bad
