### ISSUE TITLE
A tool for creating remark slides from a template and pure markdown files

### ISSUE THREAD

**Issue by igordejanovic** [gnab/remark#380]
Hi,
In case anyone is interested I've made [a little tool](https://github.com/igordejanovic/remark-compose) to help with making a consistent set of slides using remark from a HTML template and pure markdown files. I'm currently using it to migrate my lecture slides.

BTW, thanks for the great work. remark is awesome!

**Comment by abelards** [comment]
Thanks @igordejanovic -- I have added this to our wiki
https://github.com/gnab/remark/wiki/Static-Generators
