### ISSUE TITLE
Option: Don't count incremental slides as different slides

### ISSUE THREAD

**Issue by Unode** [gnab/remark#383]
Currently each increment on incremental slides (or fragments) is counted as an individual slide.  
1 slide with 3 increments it's treated as 4 slides. 

Is there any option that changes this behavior such that increments are not counted? i.e. only count `---` as slides. Perhaps something like:

``` javascript
countIncrements: false,
```

and possibily:

``` javascript
slideNumberFormat: function (current, fragment, total) {
  return 'Slide ' + current + '.' + fragment + ' of ' + total;
}
```

**Comment by sinedied** [comment]
There is already an option for this `countIncrementalSlides: false` and for the number format too, check out the wiki.

**Comment by Unode** [comment]
Thanks, missed that one.
