### ISSUE TITLE
chrome local error

### ISSUE THREAD

**Issue by mhohai** [gnab/remark#388]
![2016-11-08t17 19 18_001](https://cloud.githubusercontent.com/assets/1797676/20093481/e25fb2a0-a5d7-11e6-93e7-652457085ab1.png)
remark-latest.min.js:17 XMLHttpRequest cannot load file:///home/gshmu/Desktop/re_remark/regex_gshmu.md. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

**Comment by sinedied** [comment]
External local file loading only works if you setup a local http server, this is indicated in the docs.

Try with https://github.com/indexzero/http-server for example.

**Comment by mhohai** [comment]
@sinedied I know the http server work well.

but I send folder to some one will not...

**Comment by sinedied** [comment]
This is not a remark issue, this is a security feature of all browsers. It won't work unless you disable the security restrictions, try launching chrome from command line with the flags `--disable-web-security --user-data-dir`.

**Comment by gnab** [comment]
This is indeed a browser security feature, as pointed out by @sinedied. I would recommend embedding the markdown into the HTML file if you are sharing your slideshow files with other people.

Another option could perhaps be to put your files in something like a Dropbox public folder and share its link with other people. Then you can use a HTTP server locally when authoring the slideshow, and when other people access it remotely it will be served over HTTP and not the file system, so the cross origin requests will no longer be an issue.

**Comment by mhohai** [comment]
thanks
