### ISSUE TITLE
Use <script type="text/html"> instead of textarea

### ISSUE THREAD

**Issue by arnogues** [gnab/remark#391]
Juste for improving the code, you should you 

```
   <script type="text/html">
     <!-- HTML Code HERE -->
   </script>
```

Instead using a textarea

**Comment by gnab** [comment]
I use a textarea due to the implicitly encoding, e.g. < and > automatically becomes &lt; and &gt; respectively. So basically one can put any HTML inside the textarea except </textarea>, which is the only tag that needs to be escaped explicitly.
