### ISSUE TITLE
Get rid of Google Fonts

### ISSUE THREAD

**Issue by babolivier** [gnab/remark#392]
I have major privacy concerns about using Google Fonts.

I do what I can not to be tracked online by as many GAFAM as I can, and having to check if my slides aren't tracking me is just ridiculous.

A simple solution would be to download the fonts and place them in an assets folder.

**Comment by szpak** [comment]
There was a discussion about that. You may be interested in instruction how to use (Google) fonts locally - #194.

**Comment by babolivier** [comment]
Hi and thanks for the info @szpak.

I still have great concerns about this, even more considering this is absolutely not necessary and harmful to the user. Plus Remark's maintainers might want to remove the "Note that you need remark.js alongside this html file, but no internet connection." in the example, as Remark actually does need an Internet connection.

**Comment by gnab** [comment]
Google fonts are simply used in the boilerplate example and have nothing to do with remark as such, If you don't want to use them, you can simply leave them out.

And regarding the quote about offline usage, remark does not require an internet connection. If you reference assets that are offline, like if you use the boilerplate example, loading of the fonts will fail, but this has nothing to do with remark and will simply fallback to other, available fonts.
