### ISSUE TITLE
ES6's “const” has poor support in Safari; avoid for the time being?

### ISSUE THREAD

**Issue by tripu** [gnab/remark#395]
ES6's [`const`](http://www.ecma-international.org/ecma-262/6.0/#sec-let-and-const-declarations) is [fully supported only by the most recent version of Safari; all previous versions are flaky](http://caniuse.com/#feat=const).

*Remarkise* uses it in [a couple of places](https://github.com/gnab/remark/blob/gh-pages/remarkise.html).

Get rid of it?

**Comment by gnab** [comment]
Based on the last month's stats from Google Analytics for remarkjs.com, I would say yes :)

![image](https://cloud.githubusercontent.com/assets/158686/21364971/728666a8-c6f3-11e6-9f0b-093fad6adb0e.png)
