### ISSUE TITLE
Remark + Hugo

### ISSUE THREAD

**Issue by eueung** [gnab/remark#399]
Hi everyone,

I've just made some remark.js templates, which can be accessed via Hugo shortcodes. 

Demo:
https://eueung.github.io/hugo-remark-minion/

Repo:
https://github.com/eueung/hugo-remark-minion

Hope it'd be useful and fun for some of you.

rgds,
EM

**Comment by abelards** [comment]
Added here, thanks! https://github.com/gnab/remark/wiki/Using-with-Hugo
