### ISSUE TITLE
Adding styles to background properties

### ISSUE THREAD

**Issue by ekstroem** [gnab/remark#404]
HI, 

I'd like to make a blurred background on *some* slides. In reality I would like to be able to add the following CSS to specific backgrounds.

```
.blur {
    -webkit-filter: blur(5px) opacity(.3);
    -moz-filter: blur(10px) opacity(.3);
    -o-filter: blur(5px) opacity(.3);
    -ms-filter: blur(5px) opacity(.3);
    filter: blur(5px) opacity(.3);
}
```

Now if I have a slide that looks like this:
```
---
class: center, middle
background-image: url(pics/statcafe.jpg)
background-position: left
background-size: 100%

# Tra la la
```

then I get HTML with a div element that has a `style` given as  `style="background-image: url(pics/statcafe.jpg); background-position: left; background-size: 100%"`. 
Is it possible for me to add specific styles to this part only? If I add a `class: center, middle, blur` then the whole slide will be blurred and not just the background.

**Comment by profedrini** [comment]
have you tested it to see what happens?

**Comment by ekstroem** [comment]
Yes (at least when I wrote it more than a year ago):

>  If I add a class: center, middle, blur then the **whole slide** will be blurred and **not just** the background.

**Comment by abelards** [comment]
Let me tell it in my words, then the solution will appear by itself.

It looks like you don't want a blurred slide, because you don't want to blur text.

Rather, you want a blurred background, with a crisp foreground.

So I suggest you do just this:

```
<style>
.blurred-bg { width: 100%; height: 100% ; z-index: 1; ... }
.crisp-txt { z-index: 1000; ... }
</style>
```

```
---
# slide

.blurred-bg[
]

.crisp-txt [
  - text
]
```

I'll close this for now, feel free to reopen with more information.
