### ISSUE TITLE
Highlight doesn't work with some languages

### ISSUE THREAD

**Issue by joel-porquet** [gnab/remark#414]
Hi,

I've been using remarkjs for my lecture slides and it's been working quite well so far. Usually, I include snippets of C code or shell scripts, which are both properly highlighted. Now I'm writing slides with snippets of Makefiles and I can't get the highlighting to work. I've tried all the possible names "Makefile, makefile, mk, etc" but it's never recognized.

Any idea what could be the issue?

Thanks!

**Comment by joel-porquet** [comment]
Sorry about this non-issue. Highlight actually works, it's just the support for the Makefile language which is absolute crap in highlight.js (and doesn't match anything of a realistic Makefile).

**Comment by tripu** [comment]
@joel-porquet: I think @isagalaev will be glad if you improve [Makefile support in highlight.js](https://github.com/isagalaev/highlight.js/issues/201#issuecomment-28244519) :)

> *&ldquo;I decided to kickstart this process and implemented a basic Makefile support in `e7512d6` from what little I know about Makefiles. It's even usable as far as I see but It'd be good if you could get someone to improve it.&rdquo;*

**Comment by joel-porquet** [comment]
@tripu : FYI, I followed your advice and just spent this afternoon working on improving the Makefile support ;)
(https://github.com/isagalaev/highlight.js/pull/1489)

**Comment by tripu** [comment]
Nice, @joel-porquet :)
