### ISSUE TITLE
Can't use external CSS?

### ISSUE THREAD

**Issue by rafaelferreiraql** [gnab/remark#422]
Hello, I'm just starting with Remark, and it seems that if I try to <link> external CSS instead of using <style> (I'm using the boilerplate for now), it just breaks. In fact, even if I use both <style> and <link> it breaks all the same. I have to remove <link> to have it work.

**Comment by utdrmac** [comment]
You must be doing something wrong then because I use both external style sheets and inline CSS without issue. Here's my template:

```
<!DOCTYPE html>
<html>
  <head>
    <title>__TEMPLATE_NAME__</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link rel="stylesheet" type="text/css" href="../../share/custom-stuff.css"/>
    <style>
    	table.logfile {
    		width: 800px;
    		border: 1px solid black;
    	}
    </style>
  </head>
 <body>
    <textarea id="source">
...markdown/slide content here...
</textarea>

    <script src="../../share/remark-latest.min.js" type="text/javascript"></script>
    <script src="../../share/additional-macros.js" type="text/javascript"></script>
    <script type="text/javascript">
		var slideshow = remark.create({
			navigation: {
				scroll: false,
				touch: false,
				click: false}
		});
    </script>
  </body>
</html>
```

**Comment by rafaelferreiraql** [comment]
I took a second look at my problem, and it appears that the `title` attribute on the `<link>` was doing it.

**Comment by utdrmac** [comment]
Awesome. Issue closed then?

**Comment by tripu** [comment]
There seems to be an issue with `<link>` elements with a `title` attribute indeed.

Test:

* [`codepen.io/tripu/pen/XMrvbo`](https://codepen.io/tripu/pen/XMrvbo) works.
* [`codepen.io/tripu/pen/oZPVyZ`](https://codepen.io/tripu/pen/oZPVyZ) is identical, except that the `<link>` has `title="foo"`, and slides don't render. (Click the gears icon next to the title of the HTML panel.)

@gnab, `title` is a valid attribute of `<link>`, so in principle this looks like a bug to me.

**Comment by gnab** [comment]
A user bug that is ;)

https://developer.mozilla.org/en-US/docs/Web/CSS/Alternative_style_sheets
https://developer.mozilla.org/en-US/docs/Correctly_Using_Titles_With_External_Stylesheets

When you set the `title="foo"` attribute it becomes the preferred stylesheet, and of the looks of it, none of the remark ones are at play anymore...

**Comment by tripu** [comment]
@gnab, you're right!
I'd close this one, then.
