### ISSUE TITLE
Easy way to publish presentation as web page but minus notes

### ISSUE THREAD

**Issue by nealmcb** [gnab/remark#424]
My notes are often specific to me or to an audience, rather than generally explaining or amplifying the slides themselves. I think I'd rather publish my presentation as a web page, rather than a PDF.

So how do I keep my notes from being visible? I guess at a minimum I'd want a simple script to delete stuff between ??? and --- in the slides.md.  But I guess it could eventually be part of some sort of "build"script to put together a zip file or the like to simplify deployment.

**Comment by sinedied** [comment]
I just added an option to my [backslide](https://github.com/sinedied/backslide) tool to strip presenter notes on export, you should take a look 😉

**Comment by nealmcb** [comment]
Very cool - thanks, @sinedied

**Comment by gnab** [comment]
As publishing is not a feature of remark, using tools like backslide is the way to go on operations like this.
