### ISSUE TITLE
Prevent printing/saving; watermarking or blackout

### ISSUE THREAD

**Issue by utdrmac** [gnab/remark#425]
We use RemarkJS as our platform of choice for delivering training. We have over 1700 slides. Each training session, students want the slides first. But if I give slides first, then nobody completes the survey on the last day. So I hold the slides ransom (ie: you get them after you take the survey).

I'm thinking about hosting the slides next time, so that each student can open a URL and watch along. As I navigate, theirs navigates too. But how can I prevent them from doing Print->PDF or Save As->Web Archive? Is there some CSS I can just to watermark the pages or just blackout every slide?

**Comment by Sequoia** [comment]
This sort of behavior is user-hostile & browsers do not make it easy or complete for that reason. I don't mean that as a value judgement, just a categorization. For example:

> How do I make the window full screen and stop users from closing the window?

Browsers *intentionally* do not let you do this, as it can override the user's intentions and screw up their experience. Ditto what you're asking for.

That said, yeah you could do

```css
@media print{
    .remark-slide-content {
        display: none!important;
    }
}
```

and that _should_/might hide content from printing (print styles are notoriously flakey).

That said **if you want to truly control content, the web is not the best platform to deliver it**. That's just not how the web works. Regarding web archives, sure you could probably come up with some crazy workaround that hits a license server before rendering the page or whatever but that depends how crazy you want to get. Remember: *they have access to the markdown on the page*, and there's no way you can let them load that into their browser without letting them d/l it, as those are essentially the same thing.

**Comment by utdrmac** [comment]
@Sequoia Thanks for the CSS. All true statements. On your last point, I was thinking of making a presentation system based on socket.io. When I navigate a slide, it will send the contents to all connected to the socket and be rendered locally. That way, if they 'view source', they won't see anything but maybe 20 lines of HTML and a couple calls to JS to set up the socket. Thoughts on that?

**Comment by tripu** [comment]
@utdrmac, why not split up all those 1,700 slides in manageable batches? Then you can at least make sure students will not have all the content of the semester/week/day from the very beginning; the &ldquo;worst&rdquo; they could do is get ahead a little bit (depending on the granularity you define)&hellip;

**Comment by utdrmac** [comment]
@tripu in reality, they are broken up in to many "modules" (ie: chapters). but if you added them all up, its about that much. the class is only 4 days long. but they still want all the slides on day 1. it's not about them getting ahead; it's about them not taking the survey. it's like I hand you a beer and say 'please pay over at the counter at your convenience' and then you just walk away with a free beer or 'please pay and then you'll get the beer'
