### ISSUE TITLE
Docs: explain how to do a few popular layouts

### ISSUE THREAD

**Issue by rauschma** [gnab/remark#429]
Apple’s Keynote has a useful selection of default layouts that cover most use cases. I wouldn’t know how to replicate some of them with Remark (esp. 50% image and 100% image). Would it make sense to explain how to do so in the docs? Two-column text would also occasionally be nice to have.

![Keynote layouts](https://cloud.githubusercontent.com/assets/526114/25089772/f772b946-237f-11e7-8f21-51377e8a049d.png)

**Comment by utdrmac** [comment]
Just use CSS.

```
/* Two-column layouts */
.left-column  { width: 49%; float: left; }
.right-column { width: 49%; float: right; }

.left-column-33  { width: 33%; float: left; }
.right-column-66 { width: 66%; float: right; }

.right-column ~ p { clear: both; }
.right-column ~ ul { clear: both; }
```

**Comment by utdrmac** [comment]
For images, I made a custom macro:

```
/**
 * Returns an img tag using the parameter as either percentage or exact value
 *
 * @param {int} scale - value of scale
 * @object {this} content - path to image.
 */
remark.macros.image = function (xscale, yscale)
{
	var url = this;
	var img = document.createElement('img');
	img.src = url;
	
	if (xscale != undefined && xscale != "")
		img.style.width = xscale;

	if (yscale != undefined && yscale != "")
		img.style.height = yscale;
	
	return img.outerHTML;
}
```

Usage: 
 `.center[![:image 300px](images/master-2-slaves.png)]`
 `![:image 99%](images/migration-process.png)`

**Comment by rauschma** [comment]
Thanks! Very helpful!

**Comment by utdrmac** [comment]
@rauschma Can you close this out then if you are all set?

**Comment by rauschma** [comment]
I am! Thanks again.

**Comment by 1-2-3** [comment]
I made a template for remarkjs that contains some themes, layouts, and components. I hope it works for you.
[demo](https://1-2-3.github.io/remark-it/index-en_US.html) | [source](https://github.com/1-2-3/remark-it)
![](https://raw.githubusercontent.com/1-2-3/remark-it/master/screenshots/111.png?raw=true)
![](https://raw.githubusercontent.com/1-2-3/remark-it/master/screenshots/222.png?raw=true)

**Comment by abelards** [comment]
I referenced that in our wiki, thanks so much @1-2-3 !
https://github.com/gnab/remark/wiki/HTML-CSS-JS-samples

**Comment by 1-2-3** [comment]
> I referenced that in our wiki, thanks so much @1-2-3 !
> https://github.com/gnab/remark/wiki/HTML-CSS-JS-samples

Thank you for your recognition!
