### ISSUE TITLE
Presenter remote support?

### ISSUE THREAD

**Issue by lipop** [gnab/remark#435]
I am trying to use the presenter remote to navigate through slides, but it does not seem to work. Is there a way to bind the next button with the right arrow?

Appreciate any help!

**Comment by utdrmac** [comment]
Presenter mode as in you press 'c' to get a new window and then use the original window in 'p' mode? This works just fine. I've been presenting for the past 3 days doing this method and have not had any issues with it.

**Comment by lipop** [comment]
Hi utdrmac,

Sorry I might not be clear. What does not for me is the presenting remote, which is a clicker that allows you to turn pages. Are you using a clicker? If so can you tell me your operating system and the clicker specs?

Thanks!

**Comment by utdrmac** [comment]
I'm using Chrome on MacOS with a Logitech R400 presenter remote. I didn't have to do anything special to set it up. This is my config, if it matters. The presenter remote auto-binds left/right to the proper keyboard keys.

```
var slideshow = remark.create({
        navigation: {
            scroll: false,
            touch: false,
            click: false}
        });
```

**Comment by lipop** [comment]
Thank you Matthew. Seems to be the problem on my side. Will further check.
