### ISSUE TITLE
Presentation & presenter notes to PDF not rendered correctly

### ISSUE THREAD

**Issue by jknyght9** [gnab/remark#441]
Is there an elegant way to print the presentation and presenter notes to a PDF? I know that you have a way with printing the presentation using Chrome or Safari. Thanks.

**Comment by mathanimas** [comment]
I had the same problem, too. I found that as a quick fix, it helps to add a custom style sheet to your presentation containing:

```
@media print {
 .remark-container.remark-presenter-mode .remark-slide-notes {
  margin-top:700px;
 }
}
```

I imagine that the exact number of pixels (700 roughly works for me) may be different for various paper sizes. You may have to try different values.

**Comment by growdigital** [comment]
It would be worth looking at the print CSS stylesheet to get the slides to print out to PDF.

**Comment by grexe** [comment]
this is now covered on the [front page](https://github.com/gnab/remark#printing).

**Comment by peterj** [comment]
Closing this. @jknyght9  please re-open if Decktape doesn't fix this for you.
