### ISSUE TITLE
Official Presentation -> link back to the .md

### ISSUE THREAD

**Issue by denjn5** [gnab/remark#448]
The official example presentation at https://remarkjs.com/ uses some excellent features (e.g., columns).  It'd be great to have a link to the underlying .md file used to create it.  That would also illustrate how easy it is to use.

**Comment by utdrmac** [comment]
Just look at the HTML source. It's all there. Chrome-Mac: Apple-Option-U

**Comment by denjn5** [comment]
Ha! Perfect. And simple. Thank you.  --David

**Comment by jcrben** [comment]
@tripu @gnab is the official markdown in version control somewhere? I know I can examine the source, but unless I'm missing something that just shows me the generated HTML and not the markdown that was used to create the presentation.

**Comment by tripu** [comment]
@jcrben:
afaict, that presentation is not under version control publicly here on GH, no.
Anyway, and as @utdrmac said, the Markdown source is there, inside `<textarea id="source">`, starting at line 123. Look for `name: inverse` in the source code of the page.

@gnab: I too think it'd be a good idea to put the sample presentation inside this repo, as a handy example.
