### ISSUE TITLE
presentation mode in Linux

### ISSUE THREAD

**Issue by csrgxtu** [gnab/remark#450]
hi, i connected a second screen to my Ubuntu linux, and start my presentation in presentation mode, but can not display the PPT full screen on the second screen, got this:
![image](https://user-images.githubusercontent.com/5053620/29125848-62709db6-7d4f-11e7-9081-6f04a9f3f0ee.png)

can i only show the left content the second screen?

**Comment by utdrmac** [comment]
This is not powerpoint, don't call it PPT.

Press the 'P' key to get out of presenter mode on the 2nd screen.

**Comment by jcrben** [comment]
I think this was answered and can be closed @gnab

**Comment by peterj** [comment]
Closing.
