### ISSUE TITLE
source of the 19 slices demo

### ISSUE THREAD

**Issue by pascalandy** [gnab/remark#459]
Hi,

Did you shared the source of the 19 slices demo found at https://remarkjs.com/#1 ?
Also, is there a place where you did aggregated great presentations?

I'm running remark via jekyll in a docker container and it's great!!

Cheers!

**Comment by utdrmac** [comment]
@pascalandy View the source code in your browser. Simple.

**Comment by pascalandy** [comment]
Ok now I see. I was asking because I thought I could choose a template from the main .html but I had to manually paste the CSS stuff as well. 

It's not working working :)

**Comment by utdrmac** [comment]
@pascalandy So you can close this issue then?

**Comment by pascalandy** [comment]
Sure! 
Are you interested if I do a PR where one can use Docker / Jekyll / Remark together?

**Comment by utdrmac** [comment]
You can certainly submit one.

**Comment by peterj** [comment]
Closing.
