### ISSUE TITLE
Center the table 

### ISSUE THREAD

**Issue by zmonoid** [gnab/remark#462]
How to place the table at center?

**Comment by cjoshmartin** [comment]
Could you clarify your question? Do you mean HTML tables? if so, did you try something like this:

```markdown

.center[ 

| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |

]
```
You can read more about formatting in remark [here](https://github.com/gnab/remark/wiki/Formatting#alignment)

**Comment by mpvharmelen** [comment]
How do you centre a table on your page?

When I try:
```html
<div align="center">

| Tables        | Are           | Cool  |
| :------------ |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |

</div>
```

The table is not rendered. HTML output is exactly the same as markdown input.

This table is also rendered correctly:
```html
<div align="center">Some test</div>

| Tables        | Are           | Cool  |
| :------------ |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |
```

```html
<div align="center">Some test</div>

<table>
<thead>
<tr>
<th style="text-align:left">Tables</th>
<th style="text-align:center">Are</th>
<th style="text-align:right">Cool</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left">col 3 is</td>
<td style="text-align:center">right-aligned</td>
<td style="text-align:right">$1600</td>
</tr>
<tr>
<td style="text-align:left">col 2 is</td>
<td style="text-align:center">centered</td>
<td style="text-align:right">$12</td>
</tr>
<tr>
<td style="text-align:left">zebra stripes</td>
<td style="text-align:center">are neat</td>
<td style="text-align:right">$1</td>
</tr>
</tbody>
</table>
```

**Comment by mschilli87** [comment]
@mpvharmelen: Did you try @cjoshmartin's solution?

> `.center[`  
>  
> `| Tables        | Are           | Cool  |`  
> `| ------------- |:-------------:| -----:|`  
> `| col 3 is      | right-aligned | $1600 |`  
> `| col 2 is      | centered      |   $12 |`  
> `| zebra stripes | are neat      |    $1 |`  
>  
> `]`

**Comment by mpvharmelen** [comment]
Yes!

@cjoshmartin's solution renders the table correctly, but in a `<div class="center">` block instead of `<div align="center">`. As a result not explicitly aligned columns in the table are centre-aligned instead of left-aligned, but the table as a whole is still on the left of the slide.

**Comment by abelards** [comment]
I think there's a workaround so let's close the ticket.
#531 will be around our markdown parser, once we get a better view of all markdown problems we'll be able to dive in.
