### ISSUE TITLE
horizontal scroll bar appearing after building a new version of remark

### ISSUE THREAD

**Issue by punkish** [gnab/remark#469]
I `git clone(d)` the latest version of remark and build it using the instructions. But now I am getting a horizontal scroll bar on my slides. The back-and-forth scroll is very tiny, but it is annoying. How do I get rid of it?

**Comment by punkish** [comment]
hmmm, the horizontal scroll bar is only in Firefox, not in Safari. Any suggestions as to what is going on?

**Comment by tripu** [comment]
I can't reproduce that, @punkish.
Can you elaborate with URLs or screenshots, please?

**Comment by punkish** [comment]
hi @tripu sorry about the false alarm (and the delayed response). It was a false alarm. Turns out I had an errant div element that was at width 100% causing the overflow. Reducing it to 95% eliminated the horizontal scroll.
