### ISSUE TITLE
Unable to use *Next* and *Previous* events from presenter

### ISSUE THREAD

**Issue by paulmenzel** [gnab/remark#475]
An USB presenter includes an USB dongle, which is recognized as a keyboard device. Pressing the keys on a Logitech presenter sends the key events *Next* and *Previous* on GNU/Linux with Mozilla Firefox. Unfortunately, these are not acted upon, so the presenter cannot be used to navigate the slides.

remark.js should recognize these key events, so that presenters can be used.

**Comment by utdrmac** [comment]
I have this device, on MacOS, using any browser, and it works just fine with RemarkJS (https://www.logitech.com/en-us/product/wireless-presenter-r400)

**Comment by paulmenzel** [comment]
Interesting, I guess macOS maps the keys differently then (maybe onto the arrow keys).

**Comment by utdrmac** [comment]
@paulmenzel I just tested on my Ubuntu 16 desktop with Firefox 56. I loaded up remarkjs.com and my pointer, linked above, worked just fine.

**Comment by paulmenzel** [comment]
On 10/20/17 15:35, Matthew wrote:
> @paulmenzel I just tested on my Ubuntu 16 desktop with Firefox 56. I loaded up remarkjs.com and my pointer, linked above, worked just fine.

@matthew, strange. I used Ubuntu 17.04, Cinnamon, and Firefox 56, and it 
didn’t work. Could you please check with `xev`, what keycodes(?) your 
device sends.

**Comment by utdrmac** [comment]
Ah, I shut that machine down already. What other commands do you need me to run while I've got it up?

**Comment by paulmenzel** [comment]
On 10/20/17 15:47, Matthew wrote:
> Ah, I shut that machine down already. What other commands do you need me to run while I've got it up?

I ran only that, and saw that *Next* and *Previous* is returned in the 
output. I didn’t check anything else.

**Comment by paulmenzel** [comment]
On 10/20/17 15:49, Paul Menzel wrote:
> On 10/20/17 15:47, Matthew wrote:
>> Ah, I shut that machine down already. What other commands do you need me to run while I've got it up?
> 
> I ran only that, and saw that *Next* and *Previous* is returned in the
> output. I didn’t check anything else.

I guess `more /etc/os-release` and your desktop environment (I guess 
Unity) would be nice. If you would be willing to install [Cinnamon][1], 
and check with that, that’d be awesome.

[1]: http://www.omgubuntu.co.uk/2017/05/install-cinnamon-3-4-ubuntu-ppa

**Comment by utdrmac** [comment]
I run lightdm as GUI. That was the default.

```
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

I pressed right-right-left-left on the pointer and here's the result.

https://ghostbin.com/paste/5y9pt

**Comment by paulmenzel** [comment]
On 10/20/17 16:01, Matthew wrote:
> I run lightdm as GUI. That was the default.

LightDM is the graphical login manager. That’s used here to. It lets you 
select the desktop environment you want to use.

> ```
> NAME="Ubuntu"
> VERSION="16.04.3 LTS (Xenial Xerus)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 16.04.3 LTS"
> VERSION_ID="16.04"
> HOME_URL="http://www.ubuntu.com/"
> SUPPORT_URL="http://help.ubuntu.com/"
> BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
> VERSION_CODENAME=xenial
> UBUNTU_CODENAME=xenial
> ```
> 
> I pressed right-right-left-left on the pointer and here's the result.
> 
> https://ghostbin.com/paste/5y9pt

Thank you. The relevant parts follow.

```
KeyPress event, serial 37, synthetic NO, window 0x3a00001, root 0x1e1, 
subw 0x0, time 273948, (-1463,393), root:(33,586), state 0x10, keycode 
117 (keysym 0xff56, Next), same_screen YES, XLookupString gives 0 bytes: 
XmbLookupString gives 0 bytes: XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x3a00001, root 0x1e1, 
subw 0x0, time 274092, (-1463,393), root:(33,586), state 0x10, keycode 
117 (keysym 0xff56, Next), same_screen YES, XLookupString gives 0 bytes: 
XFilterEvent returns: False
[…]
KeyPress event, serial 37, synthetic NO, window 0x3a00001, root 0x1e1, 
subw 0x0, time 275269, (-1463,393), root:(33,586), state 0x10, keycode 
112 (keysym 0xff55, Prior), same_screen YES, XLookupString gives 0 
bytes: XmbLookupString gives 0 bytes: XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x3a00001, root 0x1e1, 
subw 0x0, time 275413, (-1463,393), root:(33,586), state 0x10, keycode 
112 (keysym 0xff55, Prior), same_screen YES, XLookupString gives 0 
bytes: XFilterEvent returns: False
```

So, my memory failed me, and it’s *Prior* instead *Previous*.

Anyway, I only had the presenter at the conference, and it didn’t work 
for me, so I cannot check again. I’ll need to find a presenter first.

Thank you for your help so far.

**Comment by utdrmac** [comment]
Issue closed then? Here's mine for $13 on ebay. https://goo.gl/LMbLGs

**Comment by paulmenzel** [comment]
On 10/20/17 16:33, Matthew wrote:
> Issue closed then? Here's mine for $13 on ebay. https://goo.gl/LMbLGs

As I can always re-open it, go ahead.
