### ISSUE TITLE
chromium --allow-file-access-from-files

### ISSUE THREAD

**Issue by patatetom** [gnab/remark#479]
hi,

this is my html file :
```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
</head>
<body>
<textarea id="source">
</textarea>
<script src="remark.js"></script>
<script>var slideshow = remark.create({sourceUrl: "test.md"});</script>
</body>
</html>
```
and my md file :
```markdown
class: center, middle

# The title
```
I use chromium 62.0.3202.62.
when I get my html page from a webserver, all is ok (thanks remark ! 👍).
when I get it locally (eg. `file://`), I've got a _normal_ cross origin error :
```
Failed to load file:///tmp/remark/test.md: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
c @ remark.js:10689

Uncaught Error
    at XMLHttpRequest.s.onerror (remark.js:10688)
    at c (remark.js:10689)
    at new r (remark.js:10752)
    at r.create (remark.js:585)
    at test.html:10
```
and when I get it locally with the chromium option `--allow-file-access-from-files` (to bypass the previous cross origin error), I've got an other error :
```
Uncaught Error
    at XMLHttpRequest.s.onload (remark.js:10684)
```
is this last error from remark ?

regards, lacsaP.

**Comment by Clafouti** [comment]
You might want to have a look at this issue : https://github.com/gnab/remark/issues/388

**Comment by joel-porquet** [comment]
After using a custom python script relying on Ninja for a while to do templating, I recently switched to the perl template toolkit (http://www.template-toolkit.org/ -- easily to install on archlinux with package "extra/perl-template-toolkit"). It has the advantage of providing `tpage`, a template renderer CLI application, by default.

File `template.html`:
```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
</head>
<body>
<textarea id="source">
[% PROCESS content %]
</textarea>
<script src="remark.js"></script>
<script>var slideshow = remark.create();</script>
</body>
</html>

File `slides.md`:
```md
[% INCLUDE "template.html" %]
[% BLOCK content %]

class: center, middle
# My big title

---
# First slide
Blabla

[% END %]
```

In my `Makefile`:
```
%.html: %.md
<tab>tpage $< > $@
```

Works great! This way, there's no need for running a local webserver. Hope it helps.

**Comment by patatetom** [comment]
hi,

thanks for the tracks !
I will try Perl template toolkit...

[@sinedied](https://github.com/gnab/remark/issues/388) for _"This is not a remark issue, this is a security feature of all browsers."_ : yes, but not all browsers because Firefox (Mozilla Firefox 56.0.2) allow XHR on file://.

[@sinedied](https://github.com/gnab/remark/issues/388) for _"try launching chrome from command line with the flags..."_ : it doesn't work for me (Chromium 62.0.3202.75), I continue to have the same mistake (Uncaught Error) as for `--allow-file-access-from-files` and, in addition, Chromium displays security warnings that are not very nice.

[@gnab](https://github.com/gnab/remark/issues/388) for _"I would recommend embedding the markdown into the HTML..."_ : yes, XHR issue disappears, but on GH (or [Gogs](https://gogs.io/)), the syntax coloring is done in relation to the file extension, and that's why I'm outsourcing the markdown.

I'm also trying to get a look at [Chromium's side](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-discuss/MoSu1JvWwP8) of the story...

regards, lcsaP.

**Comment by abelards** [comment]
Hi all, thanks for the Makefile, I've added it to our wiki:
https://github.com/gnab/remark/wiki/Static-Generators
I'm also closing the issue, but feel free to discuss other options :)
Cheers,
