### ISSUE TITLE
Allow left and right button clicks to navigate

### ISSUE THREAD

**Issue by paulmenzel** [gnab/remark#480]
At least in presentation mode, clicking on the slide with the left mouse button should go to the next slide, and clicking with the right mouse button should move to the prior slide. That is how it works for example in Evince (only in presentation mode).

It doesn’t work with Mozilla Firefox 56.0 in Ubuntu 17.10 with Cinnamon as desktop environment.

**Comment by fanlix** [comment]
middle button scroll works.

**Comment by paulmenzel** [comment]
> middle button scroll works.

Thank you for the hint. I’d still say, that clicking buttons would be easier especially with touchpads.

On the other hand, and list the right button click opens the context menu in browsers, so thinking about it again, it’s probably a bad idea to override that with something else. (I do not use the context menu at all, but other people might.)
