### ISSUE TITLE
incremental slides with left/right columns

### ISSUE THREAD

**Issue by stephentu** [gnab/remark#484]
Hi,

I'm curious if it is possible to get incremental slides working with the `.left-column[]` and `.right-column[]` construct featured [https://remarkjs.com](https://remarkjs.com). Right now, when I do

```
---
layout: false
.left-column[
## My heading 1
]
.right-column[
First statement 

--

Second statement
]
``` 

It does not render the slides incrementally. I could do something like

```
---
layout: false
.left-column[
## My heading 1
]
.right-column[
First statement 
]
---
layout: false
.left-column[
## My heading 1
]
.right-column[
First statement 

Second statement
]
```

but I plan to have several statements and having to keep them manually in sync is not ideal.

Thanks for the help!

-- PS: I'm a new user to remark.js coming from reveal.js, and the experience so far has been orders of magnitude better. Thanks for the great work!

**Comment by joel-porquet** [comment]
Have you tried the following by any chance?

```
---
layout: false
.left-column[
## My heading 1
]
.right-column[
First statement 
]
--
.right-column[
Second statement
]
```

**Comment by abelards** [comment]
What do you have in mind? 538 is closed and it's documented here now:
https://github.com/gnab/remark/wiki/HTML-CSS-JS-samples
I'm closing the ticket for now, feel free to reopen/open a new one if it's not good enough.

**Comment by mhaffner** [comment]
I can get this to work with the @joel-porquet 's solution , although it seems a little clunky. The excerpt from the "trick" referenced above is cleaner and more intuitive but I can't get it to work. E.g.,

```
# Title here

.left-column[

- Item 1
--

- Item 2
--

- Item 3
]
```

As of Nov. 2018 it seems like this is not expected to work:

> @floswald RemarkJS will not examine "inside" a div for parseable content like that. Check out this open issue with possible solution #484

So the original solution in this thread posted by @joel-porquet is still the way to go, no?

**Comment by mhaffner** [comment]
One other issue I notice is that there is a ton of whitespace between `First Statement` and `Second Statement` when using

```
---
layout: false
.left-column[
## My heading 1
]
.right-column[
First statement 
]
--
.right-column[
Second statement
]
```
This actually makes sense though since it is essentially slapping multiple div's on top of one another and there ought to be whitespace between the div's. This might not be a problem for two or three sentences, but it starts to look awkward when using a four or five point bulleted list, for instance.

**Comment by bkmgit** [comment]
This doesn't quite work for me. Had to use HTML and CSS
* https://bkmgit.github.io/tryremark/#5
* https://github.com/bkmgit/tryremark/tree/gh-pages
