### ISSUE TITLE
State of development

### ISSUE THREAD

**Issue by languitar** [gnab/remark#495]
What is the state of development of this project? Currently the fork by @tripu seems to be much more active.

**Comment by tripu** [comment]
(@languitar: thanks, but [my fork](https://github.com/tripu/remark/) isn't ahead of @gnab's upstream in any way: [diff](https://github.com/gnab/remark/compare/commonmark...tripu:commonmark), [diff](https://github.com/gnab/remark/compare/develop...tripu:develop), [diff](https://github.com/gnab/remark/compare/gh-pages...tripu:gh-pages), [diff](https://github.com/gnab/remark/compare/master...tripu:master), [diff](https://github.com/gnab/remark/compare/steps...tripu:steps).)

**Comment by tripu** [comment]
That being said, I see now that [there have been no commits to the main branch in the last three months, approximately](https://github.com/gnab/remark/graphs/contributors?from=2017-10-15&to=2018-01-08&type=c)&hellip;

@gnab, perhaps you want to nominate additional maintainers?

**Comment by gnab** [comment]
@tripu Based on how little time I have had to spend on remark the last year that is probably the best for the project. Interested?

**Comment by tripu** [comment]
@gnab: I'll be happy to share that status with others (you, and/or other contributors). Thanks!

**Comment by gnab** [comment]
@tripu Perfect. I've invited you as a contributor now, so you should have access to go crazy bananas as soon as you accept the invite I guess. Remember, with great power comes great responsibility ;)

FYI - I have started a local branch for getting rid of marked and using [markdown-it](https://markdown-it.github.io/) instead. Most custom markdown parsing have been converted into plugins, and I am tidying up stuff. So whenever I have time I'll try to finish off that work and push it. It should improve a lot of things, and correct most issues tagged with CommonMark.

**Comment by gnab** [comment]
*Collaborator was the right work. You were already a contributor :)

**Comment by tripu** [comment]
I'm in. I was in the kitchen, poke around the bookshelf, and kicked the tires. I'll behave :)

**Comment by languitar** [comment]
Good to see that things are moving forward :)

**Comment by foxik** [comment]
@gnab Any status update on the `markdown-it` integration?

**Comment by foxik** [comment]
@gnab If you have the local markdown-it branch, would you consider pushing it as a new branch to the repo? I would like to do the conversion (at least for myself), and it would be a great starting point.

**Comment by matrixise** [comment]
Hi @tripu and @gnap what’s the status of the project? Thank you

**Comment by utdrmac** [comment]
There's a PR #533 which is the most "active" thing here. Have not seen much of anything else happening. It's a shame as this is a really great project that we use almost daily.

**Comment by abelards** [comment]
Hi all!
Thanks your work on remarkjs, I use it and love it.
I'm ready to help, but I have as little time as anyone else.

Since no one likes bug triage, I took a few minutes to start.
Feel free to close 4.5% of issues ;)

Questions that have been answered:
- #263 how to do comments
- #363 comparison with reveal
- #548 where is the maintainer

Problems that have been fixed:
- #302 provide example
- #357 solved
- #528 CSS typo

A very quick yes or no:
- #305 default CSS for blockquotes


Cheers,

**Comment by peterj** [comment]
@gnab @tripu do y'all need any help with reviewing/merging PRs/triaging issues etc?

**Comment by tripu** [comment]
@matrixise: I have been busy with (proper) work for months, I'm sorry.
@peterj: help welcome from my side!

**Comment by peterj** [comment]
@tripu there has been a lot of fixes/PRs merged since the last release in 2016. Perhaps the first thing we could do is to go through open PRs and see which ones can/should get merged, and then create a new release (the last one was in 2016 :)).  I can also look through the open issues and do a quick triage (looks like @abelards has already done some work there, but that's from 2018 :)).

**Comment by utdrmac** [comment]
Is there a bounty program or some way to donate $$ to help bring things up to date?

**Comment by tripu** [comment]
@peterj: agreed; triaging and reviewing pending notifications (issues, mentions, comments) is the first thing I'd do myself when I find some time to get back to this project. Whatever work you do in that regards will be welcome. Feel free to comment on items to reflect your assessment of complexity/priority, and to leave your review on the PRs you deem most relevant!

@utdrmac: not that I know; @gnab will know better.

**Comment by gnab** [comment]
I once had a plan to rewrite remark, getting rid of marked and rather use commonmark, but that never happened. So, perhaps the best is to accept some of the markdown headaches that comes with marked, and focus on fixing other bugs and doing features.

If anyone want to be promoted to contributors, in addition to @tripu, and help out, please let me know. 

@abelards, @peterj?

**Comment by abelards** [comment]
It'd be an honor!
I'm not promising anything soon but I can help in tiny ways, and tiny things add up :)

**Comment by peterj** [comment]
@gnab I would love to help out.

**Comment by gnab** [comment]
Awesome! You are both invited to become contributors now.

**Comment by abelards** [comment]
So... I don't really remember the issue count 15 days ago, but I think it was above 160.
It's now below 125, and most issues are now tagged.
There's been some pruning (not too aggressive either), some documentation in the wiki...
Thanks to anyone who's active these days, it feels good :)

I'm not planning to touch at latex or syntax highlighter stuff anytime soon, and it would take some time to dive in all markdown issues, but I will perhaps have a look at the "screen resizing" or "printing" issues, or develop a feature I want: an overview of slides that's easy to display and/or print.

Cheers,

**Comment by dvberkel** [comment]
Hi @gnab,

I love the project and started helping out. Unfortunately, I am not a contributor in the GitHub sense, so I can't label issues and some other things.
I would love to contribute back. Being a contributor would help. Could you invite me as a contributor?

**Comment by matrixise** [comment]
Hi everyone,

Just checking in to see if there’s any update on the state of the project. Remark has been such a brilliant tool over the years — simple, elegant, and extremely useful for Markdown-based presentations.

However, it looks like the project has been inactive for quite a while. Does anyone have news from @gnab, or know if there’s a plan to maintain or hand over the project?

I’d also be very interested to know if there are any actively maintained forks or similar projects that follow the same philosophy. Remark is really a unique and valuable tool, and it would be great to see it live on in some form — or to help support efforts to keep it going.

Thanks in advance!
