### ISSUE TITLE
tests are broken

### ISSUE THREAD

**Issue by languitar** [gnab/remark#502]
After the last merges the tests are broken now.

**Comment by tripu** [comment]
@gnab, this is the commit that broke the build: 6350506494ac19b43158b3be6ed1d3cca23dd8e4

Those changes about backticks and inline code come from #456 (but that build was fine).

Another change among the few you put together into a bunch in 6350506494ac19b43158b3be6ed1d3cca23dd8e4 is the upgrade from `marked` `0.3.1` to `0.3.9` (see [that changelog](https://github.com/chjj/marked/compare/v0.3.1...0.3.9)). However, I've run tests at 6350506494ac19b43158b3be6ed1d3cca23dd8e4 downgrading first to `marked` `0.3.1`, and the build fails, too.

Any idea what might be wrong?

**Comment by tripu** [comment]
Fixed by @bfagundez (h/t) in #519.
