### ISSUE TITLE
Setting font color in content class does not work for nested lists

### ISSUE THREAD

**Issue by 942kid** [gnab/remark#508]
When trying to set font color for some text in a nested list, I found that the [content class](https://github.com/gnab/remark/wiki/Markdown#class) does not work in the *sub-items* of the nested list. Here is an [example](https://codepen.io/uuoofan/pen/gvwvBv). 

I found a temporary workaround by change the *color of links*, which works no matter where the link locates. Any suggestions would be appreciated!

**Comment by tripu** [comment]
@942kid, it's a Markdown issue in your example. In this case, [you need 1, 2 or 3 spaces (but not 4) to indent the sub-list](http://spec.commonmark.org/0.28/#list-items). eg:

```
* .red[One]
  - .red[one]
  - [two](#)
```

instead of

```
* .red[One]
    - .red[one]
    - [two](#)
```

**Comment by 942kid** [comment]
@tripu Thank you for your response!
