### ISSUE TITLE
How to use remark.js functions to convert markdown to html?

### ISSUE THREAD

**Issue by pinbo** [gnab/remark#513]
Dear remark contributors,

Thanks a lot for creating remark, and it is really a powerful tool to create slides. I really like the remark macros and class formatting, for example, `.red[this is red font]`. I want to use remark to just convert my markdown to HTML, so I can use all these powerful extensions in my blogdown posts. I am new to javascript and after reading the codes, it seems `remark.convert` is the function I need, but I am not sure how to use it (such as what are the arguments). Could you help me on that? I would really appreciate it. This will be also easy for me to convert slides to notes for printing. Thanks!

Junli

**Comment by gshmu** [comment]
@pinbo I think it's already html, not markdown.
html contained js...

**Comment by tripu** [comment]
@pinbo: Remark does *not* do the conversion *Markdown&nbsp;&rarr;&nbsp;HTML* itself; instead, it relies on this other project for that: [Marked](https://marked.js.org/#/README.md#marked). Marked is available as an npm module, and also on the browser; check it out :)

**Comment by pinbo** [comment]
Thanks, @gshmu and @tripu
