### ISSUE TITLE
Support Smart/Curly Quotes and Dashes

### ISSUE THREAD

**Issue by xaprb** [gnab/remark#514]
Remark is awesome! My only wish is that it'd automatically convert straight quotes to curly quotes, and two or three dashes to en- and em-dashes.

**Comment by xaprb** [comment]
Looks like this is a duplicate of #266.

**Comment by ernstki** [comment]
@xaprb If this is still important to you, you might consider re-opening this issue.

Apologies to [Gruber](https://daringfireball.net/projects/smartypants/), but in 2020, I'm not sure if the typical developer-off-the-street is going to even know what SmartyPants is. Or was.

But it makes sense to search the issue tracker for "smart quotes" or "curly quotes," which is exactly how I ended up here.
