### ISSUE TITLE
Inconsistent sub-slide behavior with nested bullet points

### ISSUE THREAD

**Issue by utdrmac** [gnab/remark#516]
Consider the following RemarkJS/Markdown:

```
---

* AAA

--
    * ...BBB
--
    * ...CCC
```

The above produces the desired effect: First show AAA, then "next slide" show BBB as a sub-bullet, then "next slide" show CCC at same sub-level as BBB.

But why does there have to be a blank link between `* AAA` and `--`?

Consider this:
```
* AAA
--
    * ...BBB
--
    * ...CCC
```

In the above, `* ...BBB` is appended to the previous point so it looks like `* AAA*...BBB`

Now consider this (line return between each bullet)
```
* AAA

--
    * ...BBB

--
    * ...CCC
```

In this, AAA shows fine. BBB shows fine. But when you navigate to slide 3, you see CCC but the spacing between AAA/BBB/CCC has completely changed. For some reason, in this case, `<p>`'s are added to each `<li>`. Why is that? This doesn't happen for just AAA and AAA/BBB. It only happens in case of 3+ subelements/subslides.

![screen shot 2018-04-02 at 4 29 42 pm](https://user-images.githubusercontent.com/4413670/38217282-6ac28742-3693-11e8-94d8-d77fe1a7133d.png)

![screen shot 2018-04-02 at 4 30 19 pm](https://user-images.githubusercontent.com/4413670/38217281-6ab2bdda-3693-11e8-954d-3b3f5adfd18f.png)

<img width="463" alt="screen shot 2018-04-02 at 4 29 08 pm" src="https://user-images.githubusercontent.com/4413670/38217279-6aa32ec4-3693-11e8-999b-5f278e34f13b.png">

![screen shot 2018-04-02 at 4 30 11 pm](https://user-images.githubusercontent.com/4413670/38217284-6ad850b8-3693-11e8-94c2-471a203fb06a.png)

**Comment by utdrmac** [comment]
*bump* Hoping someone has a fix in the works for this. How do I start a bounty?

```
---

## Containers (LXC)

* OS-level virtualization method
--

* Allows running multiple, isolated systems, using a single kernel ("host")
--

* Kernel provides _cgroup_ functionality
    * CPU/memory/disk/network
    * No need for complete OS install
    * No device emulation/hypervisor
???
cgroup - control group (created by google, merged into 2.6.24, 2008)
--

* "Lightweight" virtual machine
--

* Local file system
--

* Accessible over network
--

* Container itself is isolated process
--

* "Baremetal" performance
```

**Comment by utdrmac** [comment]
@tripu Any discovery here? This is issue is highest priority for us @Percona.

**Comment by utdrmac** [comment]
Here's another example where return inside blockquote creates issues similar to above:

    ---

    ## Run Sample Application

    * On `app`, start the application and verify
        * Use another window for this or use `screen`
    ```sql
    app# prepare_sysbench_oltp.sh

    app# run_sysbench_oltp.sh
    ```
    * Is replication flowing to all the nodes?
    * Observe the sysbench transaction rate

![screen shot 2018-06-25 at 4 08 15 pm](https://user-images.githubusercontent.com/4413670/41876057-3f8a939e-7892-11e8-98cc-63ae1d261947.png)

**Comment by mschilli87** [comment]
@utdrmac 
> This is issue is highest priority for us @percona.

So where is your PR to fix it? :wink:

**Comment by utdrmac** [comment]
@mschilli87 I'm not a programmer. I rely on the code creators to fix bugs.

**Comment by mschilli87** [comment]
@utdrmac: I think 5 messages to > 200 people should be sufficient to point out a problem without offering a solution. The people working on this usually do so for free in their personal time after work. So I doubt that by 'bumping' this issue it is going to be solved sooner.

**Comment by utdrmac** [comment]
I spent the better part of today researching more into this. I discovered that having 4 space indentation produces an incorrect result though I'm not sure why. For whatever reason, the nested bullet point line is having an additional carriage return appended to the end. This appended line then gets sent to Marked for rendering. According to the Commonmark spec, the extra carriage return will create a "loose" list which adds the p tags. Ok, fine but why is an additional return being added in the first place? There's no difference between the above line: "foo<blank><separator>" and "foo1<blank><separator>" Why is foo1 being treated differently? I found 1 possibility which is a regex match against the beginning 4 spaces which matches CODE in lexer.js. I tried modifying this regex to match against 5 spaces, but that did not change anything.

![4spaces](https://user-images.githubusercontent.com/4413670/42005198-de1f29c8-7a38-11e8-9853-35ac46e7e0f4.png)
![3spaces](https://user-images.githubusercontent.com/4413670/42005199-de3005a4-7a38-11e8-85c8-e7bf7646dcc1.png)

**Comment by theseer** [comment]
As far as I know, indentations have meaning in markdown.
So, when using 2 spaces for subpoints like this:

```
- Topic
  - Sub topic 1
```

The `Sub topic 1` is recognized as a child bullet.
When adding `--` with an empty line following:

```
- Topic
--

  - Sub Topic 1
--

  - Sub Topic 2
```

You should get the desired effect.

**Comment by abelards** [comment]
Looks fixed, so I'm closing it and documented it in the wiki
https://github.com/gnab/remark/wiki/HTML-CSS-JS-samples
