### ISSUE TITLE
help with error on loading .md files

### ISSUE THREAD

**Issue by cg-cnu** [gnab/remark#518]
Hello ! 👋 I am using remark for a while and its amazing! 😃 

I have created a template project to use for myself. It gets a list of `md` files and render them based on the `template.html` file. You can see the example here... https://cg-cnu.github.io/remark-template/
and the source here...https://github.com/cg-cnu/remark-template

As you can see, there is no error message in the console when loaded online, but if you clone it locally and run it, it will show the below error. 

```
XML Parsing Error: syntax error
Location: file:///path/to/file/.../remark-template/static/md/template1.md
Line Number 2, Column 1:
```

I am not exactly sure, if it is an issue with remark or the way am dealing with loading md files.
It would be great if someone can give an input. 

Cheers!

**Comment by isao** [comment]
I'm new to remark. Using the Getting Started code over http, I failed to get any slides rendering with:

    <script src="https://remarkjs.com/downloads/remark-0.5.9.min.js"></script>
    <script>remark.create({sourceUrl: 'source.md'})</script>

Then I downloaded and used the latest release `0.14.0`, and my slides rendered.

**Comment by tripu** [comment]
@cg-cnu, does &ldquo;:+1:&rdquo; mean that you made it work with those tips? :)

**Comment by tripu** [comment]
(No response from user, and can't reproduce or it's specific to the user's setup.)
