### ISSUE TITLE
gnab.github.io/remark/ redirects to HTTP

### ISSUE THREAD

**Issue by pin3da** [gnab/remark#524]
Hi, I recently noted a problem about HTTP/HTTPS redirection.

I have some (old) slides which use the link `https://gnab.github.io/remark/downloads/remark-latest.min.js` and when the browser tries to resolve that, it is redirected to `http://remarkjs.com/downloads/remark-latest.min.js`. The problem is that browsers block mixed active content ([reference here](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default)) and the code cannot be retrieved.

In my particular case, I could replace the URL in all my slides, but I think it would be great if you can redirect to HTTPS because it may be affecting more people.

Thank you for your great work with remark!

**Comment by szpak** [comment]
You can use more direct link: https://remarkjs.com/downloads/remark-latest.min.js

Nevertheless, it's a good point. `https://gnab.github.io/remark/downloads/remark-latest.min.js` redirects to `http://remarkjs.com/downloads/remark-latest.min.js`.

**Comment by andreadellacorte** [comment]
Just ran into this issue myself :)

**Comment by pin3da** [comment]
Hi @hartwork. The problem is solved now, thanks :+1:
