### ISSUE TITLE
Highlight.js not up-to-date: multi-line docstrings in Python not highlighted

### ISSUE THREAD

**Issue by JPFrancoia** [gnab/remark#534]
Hi,

I'm about to give a talk with a lot of Python code. Some of this code contains docstrings (multi-line docstrings). Sadly they are not highlighted properly: only the first line of a multi-line docstring is highlighted. The issue was reported here: https://github.com/highlightjs/highlight.js/issues/1322, but apparently the problem comes from remark.js. Is there a fix for that? Even a dirty one (I need this urgently).

Sorry if I sound vindictive, this is not at all my mindset. My code just doesn't look professional if it's not highlighted properly.

Thank you

**Comment by julienw** [comment]
There's been some fixes for JSX support too.

Is the right fix updating https://github.com/gnab/remark/blob/b658a0c61434e4fe1ccec75ef254f4a78a13ebef/make.js#L28 and run `make highlighter` ?
