### ISSUE TITLE
bullets appearing sequentially in 2-column slide?

### ISSUE THREAD

**Issue by floswald** [gnab/remark#538]
I tried to replicate the *making points* example in the 2-col layout:

```
.col-6[
  ### Left column

  - I'm on the left
  --
  
  - It's neat!
]
```

but instead of sequentially showing the bullets, it renders *I'm on the left* as a heading. am i not understanding how to use this feature properly? thanks for your help!

**Comment by utdrmac** [comment]
@floswald RemarkJS will not examine "inside" a div for parseable content like that. Check out this open issue with possible solution #484 Here's my solution for you: https://codepen.io/anon/pen/zJzBee

**Comment by floswald** [comment]
hey! that could be a solution. can you please explain why that works though? in particular, this code here

```
.col-6[
  ### Left column

  - I'm on the left
  - It's neat!
]
.col-6[
  ### Right column

  - I'm on the right
  - I love it!
]
```
produces a left and a right column in the backslide demo, not in your codepen though? (sorry if i'm a bit slow here). basically im surprised that in your example everything lines up in the left column?

**Comment by utdrmac** [comment]
remarkjs parses .<whatever>[ content content ] into <div class=whatever>content content</div>. "--" and "---" are slide separators. remark does not look "inside" the .[] for slide markers. Your code sample does not work in my codepen because I don't have an CSS loaded. If you look at the demo, you'll see col-6 defined in the CSS.

Here's what I use in my CSS

```
/* Two-column layouts */
.left-column  { width: 49%; float: left; }
.right-column { width: 49%; float: right; }

.left-column-33  { width: 33%; float: left; }
.right-column-66 { width: 66%; float: right; }

.left-column-66  { width: 66%; float: left; }
.right-column-33 { width: 33%; float: right; }

.right-column ~ p { clear: both; }
.right-column ~ ul { clear: both; }
```

**Comment by abelards** [comment]
Thanks for the answer, I added it on the "knowledge base" and I'm closing the ticket.
https://github.com/gnab/remark/wiki/HTML-CSS-JS-samples
