### ISSUE TITLE
Background scale overridden by inverse class

### ISSUE THREAD

**Issue by kscarlett** [gnab/remark#542]
When adding a background image to a slide together with the `inverse` class, the inverse class overrides the styling that's supposed to scale the background image to fit. I assume this isn't the intended behaviour?

I fixed this on my end by adding adding a style and overriding the background scale with `!important`.

**Comment by abelards** [comment]
How do you add your background image?
I think you can probably add more specific CSS selector so it "speaks louder" than `.inverse`.
Closing the ticket for now since it's only CSS (even if remark's CSS) and not really remark features.
