### ISSUE TITLE
Support kramdown

### ISSUE THREAD

**Issue by alexcarrega** [gnab/remark#546]
Is it supported? If yes, is it possible to use it and how?

**Comment by igorsantos07** [comment]
would be great if this was more than a one-line request, explaining what's that and why it should be supported. from a quick google I see it's a Ruby parser with some extensions? if there's no JS library with these (it seems there's only PHP and Ruby), the answer is certainly going to be **no**.

**Comment by peterj** [comment]
I agree with @igorsantos07. Please re-open with more information on what kramdown is and what would it entail to support it. Closing for now.
