### ISSUE TITLE
Where is the maintainer?

### ISSUE THREAD

**Issue by matrixise** [gnab/remark#548]
Since some months, there is no updates of this project.

Is there a living fork of this project?

Have a nice day,

**Comment by mschilli87** [comment]
@matrixise: Have a look at https://github.com/gnab/remark/issues/495.

**Comment by utdrmac** [comment]
@tripu @gnab Any updates here?

**Comment by ssbarnea** [comment]
I ended up here while trying to find a good code based presentations solution and it seems that the web is full of nice projects that become abandonware. 

At least we could all check date of last commit, how many PRs are open and why they are not merged  and bugs. The best one I found didn't had any activity for 3 months but I am still looking.

**Comment by utdrmac** [comment]
It's a big shame this one has become abandoned; certainly far easier to use for quick presentations than powerpoint/google slides and super simple to collaborate with.

**Comment by mschilli87** [comment]
Well, @abelards triaged some issues in November identifying several resolved ones but those are still open as of today...
I guess it takes at least one person to actually step up and just take the lead. :wink:

**Comment by PierreMarchand20** [comment]
It is really a shame, I discovered it recently and I really prefer this one compared to reveal.js for example. It is so easy to modify the themes and to do what you want with it...

**Comment by waja** [comment]
> It is really a shame, I discovered it recently and I really prefer this one compared to reveal.js for example. It is so easy to modify the themes and to do what you want with it...

Blaming is nothing that helps guys. Maintaining OSS is hard work, especially keeping it up. If you never had to do it, I would recommend stop throwing shit. Being there, done that.

Anyway ... looking into https://github.com/gnab/remark/commits/develop indicates that @gnab is still alive!
@gnab maybe it is a good idea to create a team of people you think that are skilled enough and that you trust and can work with? Maybe that helps to spread the load?

**Comment by utdrmac** [comment]
@gnab Would donations help get some more activity on this project? I do believe there are several businesses that use this project that would be happy to donate.

**Comment by PierreMarchand20** [comment]
@waja I was not blaming, just showing interest for this really nice repo hoping that it will motivate someone to maintain it, especially now that I see reveal.js everywhere while I prefer by far this one. Sorry if it came out wrong...

**Comment by abelards** [comment]
Anyway, I'm willing to spend some time here and make things easier.
Let me know where I can help: I can help triage, write doc, whatever.

I'm a decent JS coder but I usually don't have time to go deep into topics, so I can review or suggest stuff, but "hard code" is likely not for me.

If enough people join me, we can help @gnab effectively.

I didn't feel aggressivity in the last comments, but the issue's text can sound passive-aggressive for an overworked maintainer. If anyone talks with the author on any other topic, let him know he has some friends willing to help :)

**Comment by yihui** [comment]
How about releasing a new version? The last version, 0.14.1, was released more than 2 years and 3 months ago: https://github.com/gnab/remark/commit/f66744eca With a new release, some of the existing issues could be closed, such as #478.

**Comment by abelards** [comment]
So it's done, I'm glad @gnab gave me access. I'll triage some easy stuff then perhaps go to the hard things.

Help me help you: if you really want something, give me the first steps or the outline ;)
Also feel free to tell me if you disagree with anything I do, or if you'd do it differently.

Cheers,

**Comment by yihui** [comment]
@abelards Great! As I suggested above, it will be fantastic if we can have a new release after three years of no releases. Thank you!

**Comment by peterj** [comment]
+1 on what @abelards said. 

Let's sync up and talk about cutting a new release!

**Comment by abelards** [comment]
I'm suggesting we close this issue since it's getting better.
It's nice to debate and centralise good wills, perhaps we'll need more of that in the future,
but right now we need less issues to have a clearer mind :)

I'm labeling this as "waiting for input" (BTW we might want "waiting for USER input" and "waiting for CONTRIBUTORS input"), until several of you agree we can close this.

**Comment by matrixise** [comment]
Yep, we can close this issue. 

Thanks
