### ISSUE TITLE
README.adoc link issues

### ISSUE THREAD

**Issue by hartwork** [gnab/remark#549]
Hi!

I noticed two 404s and one mis-render among the links in `README.adoc`:
- 404 @ https://kjbekkelund.github.com/nith-coffeescript
- 404 @ https://kjbekkelund.github.com/js-architecture-backbone
- mis-render @ http://torgeir.github.io/busterjs-lightning-talk/

Anyone have a minute to fix these?

Best, Sebastian

**Comment by peterj** [comment]
I can't find these links anywhere. Feel free to re-open and add a link to an actual file where these links need to be fixed/removed.

**Comment by hartwork** [comment]
The first two were removed in 4cf11b9daca0c503eacebffdf4298add31585686. The third — http://torgeir.github.com/busterjs-lightning-talk — is still in there and the page does not serve value today. Please re-open the issue.

**Comment by peterj** [comment]
Can you point me to the file/branch where you see this link?

**Comment by hartwork** [comment]
> Do you mind creating a quick PR for this?

Here you go: #595

**Comment by peterj** [comment]
Thanks for fixing!
