### ISSUE TITLE
Do we support localization for slide?

### ISSUE THREAD

**Issue by LinuxSuRen** [gnab/remark#556]

**Comment by abelards** [comment]
Hi @LinuxSuRen -- can you explain a bit more what you're expecting?
Remark is a static HTML tool so I'm not sure what you would want it to do.

If I really had to localize remark presentations, I guess I'd generate the markdown to have

.l10n.en[Hello]
.l10n.fr[Bonjour]

and then some JS to get the browser's locale (mine's french), hide all .l10n, then show all `.l10n.fr` -- could that be what you're looking for?

**Comment by LinuxSuRen** [comment]
It's been a long time. I just forgot why I create this issue. I'm ok to close this until I remember it.
