### ISSUE TITLE
How can I add "fork me on gitlab" ribbon css?

### ISSUE THREAD

**Issue by larrycai** [gnab/remark#558]
I want to add "Fork me on Gitlab" ribbon in the remark.js https://alvarolopezborr.gitlab.io/gitlab-fork-ribbon-css/ 

How can it be done? 

Rgs, Larry

**Comment by noahp** [comment]
For me, adding the .css like to my `index.html` like this (after copying into a local directory):
```html
<!DOCTYPE html>
<html>
<head>
  <title>Title</title>
  <meta charset="utf-8">
  <style>
    @import url("gl-fork-ribbon.css");
...
```

And inserting this element on a slide:
```markdown
<a class="gitlab-fork-ribbon" href="http://url.to-your.repo" title="Fork me on GitHub">Fork me on GitHub</a>
```
Worked!

**Comment by peterj** [comment]
It might be useful to add this to a wiki page. @abelards what do you think of creating a Misc category in the wiki where we can add things like these there?

**Comment by abelards** [comment]
@peterj good idea, it's done: https://github.com/gnab/remark/wiki/HTML-CSS-JS-samples
