### ISSUE TITLE
make incremental slides show incremental presenter notes

### ISSUE THREAD

**Issue by grosser** [gnab/remark#561]
I'm doing a few long slides and would love to have my presenters notes show up for each bullet point, something like this:

```
a
--
b

???

notes for a
--
notes for b
```

**Comment by vdepabk2t** [comment]
Does this work for you?
```
a
???
notes for a
--
b
???
notes for b
```

**Comment by grosser** [comment]
thx, that works!
one remaining issue is that notes get combined in presenter mode, but
that's only really an issue when having more notes then the page can show.

NOTES FOR CURRENT SLIDE
notes for a
NOTES FOR NEXT SLIDE
notes for a
notes for b

**Comment by grosser** [comment]
I added that to https://github.com/gnab/remark/wiki/Markdown
