### ISSUE TITLE
Feature Request: Show presenter notes on tablet

### ISSUE THREAD

**Issue by amueller** [gnab/remark#567]
Many of my students look at the slides on their tablet. However, because there is no keyboard they can not activate the presenter notes - at least in no way that I'm aware of. The same goes for phones.
Maybe showing a button on mobile or using a different URL or something like that would be possible? (Or maybe there's a way I'm overlooking)

**Comment by mschilli87** [comment]
Which OS for tablets comes without a virtual keyboard that one can activate, press <kbd>P</kbd>, and de-activate?
This is not saying your proposed feature wouldn't be useful for some people.

**Comment by amueller** [comment]
Android and iOS afaik? Or I'm just a bad user. I haven't been able to do it
on my android phone. Might not be googling the right thing?

**Comment by scotthewitt** [comment]
You can added a p between the # and the slide number to cause the presenter notes to open by default.

https://remarkjs.com/#1

Becomes

https://remarkjs.com/#p1

You can then either share the note open link or create a link in the slide show to open the notes.

Maybe this would work?

**Comment by amueller** [comment]
Awesome, yes that's sufficient!
Is that documented? If so I must have missed it.
