### ISSUE TITLE
What's going on?

### ISSUE THREAD

**Issue by BenTearzz** [gnab/remark#572]
@gnab so currently it seems like there's a lack of communication. I'm sure you have good reason for it, and you're probably very busy.

It doesn't seem like things are going the right way though, and especially not when it comes to the pace. Most of the issues aren't getting replies, and at least 1/3 of them could probably be closed. 

A new release isn't anywhere in sight, and changes to the wiki are non-existent.

A reply explaining what's going on and what's going to happen could clarify quite a bit. Perhaps getting some trustworthy collaborators could be a good idea. _(I personally would like to become one, even though JavaScript isn't my main language. And if not for the development, then for the issues, update on the wiki and perhaps a new release)._

I think that people as much as me, would like to get an update in terms of what's going to happen to Remark.

**Comment by jmankoff** [comment]
@BenTearzz @gnab Also happy to help if I can in any way. I (and I'm many others) have committed lots to this project in the form of slide decks that would need to be rewritten if it goes away. That investment means we're all invested in the project's success and happy to help make it happen if we can!

**Comment by yihui** [comment]
Yes, we all love remark.js and want to help, as indicated in #548. However, I suggest that you close this issue and keep the discussion in #548 (for the reason I just explained in #571).
