### ISSUE TITLE
remark with typescript

### ISSUE THREAD

**Issue by 3axap4eHko** [gnab/remark#656]
I'm using remark in typescript project and it throws an Error
```
Details:

    /home/zource/projects/zource/api/node_modules/remark/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import {unified} from 'unified'
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import { remark } from 'remark';
```
code example
```
import { remark } from 'remark';
import remarkHTML from 'remark-html';

export default function(source: string) {
  return remark()
    .use(remarkHTML)
    .process(source);
}
```

**Comment by tripu** [comment]
What is `remark().proces()`? I don't recognise that method.

Also: typo there? (`proces` instead of `process`)?

**Comment by 3axap4eHko** [comment]
@tripu it was a typo

**Comment by 3axap4eHko** [comment]
@tripu why did you close the issue?

**Comment by tripu** [comment]
> @tripu why did you close the issue? The typo was only in the issue description lol

@3axap4eHko: OK, sorry. Your response wasn't very clear.

But I understand now: you are using [npm package `remark`](https://www.npmjs.com/package/remark), which is [this tool](https://remark.js.org/), which (in spite of the name) has nothing to do with [this project here](https://remarkjs.com/).

Go here instead: https://github.com/remarkjs/remark/issues

**Comment by 3axap4eHko** [comment]
Oh sorry about that 😄

**Comment by moslem-parsarad-dev** [comment]
just fix it.
