### ISSUE TITLE
Logging/tracing possibility

### ISSUE THREAD

**Issue by kkokosa** [gnab/remark#662]
It is more question than a bug report - is there possibility to trace/print somehow how the slide is being processed? I have situation that without any sense, one part of incremental slides is not displayed. And I can't have any point of entry of trying to understand what's going on there. 

Just for reference, this is the slide:

```
---
### Generations

Advantages:

--
- collect only one generation (and younger) - less *mark*/*sweep*/*compact* work to do (which makes smaller overhead, shorter pauses)

--
- more often collect young generation (recently created objects) - it should be **productive**, most of them will die (well, "infant mortality" 😱)

--
- avoid processing the old, surviving objects again and again

--
Drawbacks:

--
- need to handle references between generations

--
- violating expected behavior may be painful
```

And, "Drawbacks" is not printed.

**Comment by tripu** [comment]
I don't remember about debugging/verbose options off the top of my head.

One thing you can do is check how `marked` (that's the Markdown library we use here) processes your input: [live test](https://marked.js.org/demo/?text=---%0A%23%23%23%20Generations%0A%0AAdvantages%3A%0A%0A--%0A-%20collect%20only%20one%20generation%20(and%20younger)%20-%20less%20*mark*%2F*sweep*%2F*compact*%20work%20to%20do%20(which%20makes%20smaller%20overhead%2C%20shorter%20pauses)%0A%0A--%0A-%20more%20often%20collect%20young%20generation%20(recently%20created%20objects)%20-%20it%20should%20be%20**productive**%2C%20most%20of%20them%20will%20die%20(well%2C%20%22infant%20mortality%22%20%F0%9F%98%B1)%0A%0A--%0A-%20avoid%20processing%20the%20old%2C%20surviving%20objects%20again%20and%20again%0A%0A--%0ADrawbacks%3A%0A%0A--%0A-%20need%20to%20handle%20references%20between%20generations%0A%0A--%0A-%20violating%20expected%20behavior%20may%20be%20painful%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master). And yes, it interprets that part weirdly. If you insert an empty line between `--` and `Drawbacks:` it looks better, but still Remark does not show that line, and the list looks broken after that part.

But I found a workaround: see [this pen](https://codepen.io/tripu/pen/rNzNymO) (the second slide).

I hope that helps!

**Comment by kkokosa** [comment]
Thanks, indeed it helps! And `marked` live test is also super useful.
