### ISSUE TITLE
Could not install remark in Rstudio

### ISSUE THREAD

**Issue by damienbelveze** [gnab/remark#673]
Hi, 

I have tried to install in Rstudio remark package with both archive files tar.gz and zip that you made available but could not succeed. 
I have also tried to install it directly from github using the command install_github("gnab/remark") which worked fine with other R packages found on github but not with yours ; I got the following error: 

"Erreur : Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found"

Would you please help me to understand where the problem comes from?

Regards,

**Comment by gadenbuie** [comment]
Hi! This repo isn't an R package, so it's expected that `install_github("gnab/remark")` doesn't install remark in RStudio. You are probably looking for the [xaringan R package](https://github.com/yihui/xaringan).

**Comment by damienbelveze** [comment]
Thank you for your quick answer. Xaringan R package is actually what I need.
