### ISSUE TITLE
Readme: "other interesting stuff" links don't work anymore

### ISSUE THREAD

**Issue by adamkusmirek** [gnab/remark#674]
As stated by the resulting 404:

```
Subdomains of github.com are deprecated for GitHub Pages. 

They will not redirect to github.io after April 15, 2021.
```

 [related gh blog entry](https://github.blog/changelog/2021-01-29-github-pages-will-stop-redirecting-pages-sites-from-github-com-after-april-15-2021/)

**Comment by tripu** [comment]
Fixed by @adamkusmirek themselves in #675.

Thank you!
