### ISSUE TITLE
Cannot run mocha-chrome tests

### ISSUE THREAD

**Issue by adamkusmirek** [gnab/remark#676]
My Specs:
```
os: Fedora 32
node: v18.0.0
npm: v8.6.0
```

Since I could not find anything on this in the wiki:
I checked out the project and ran `node make` and got this in the test segment:

```
Running tests...
Executing command "/home/adam/projects/remark/node_modules/.bin/"mocha-chrome test/runner.html
Promise Rejection:  Error: connect ECONNREFUSED ::1:35861
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 35861
}
```
I suppose that this is `mocha-chrome` trying connect to a headless chrome? Or is this something else?
If so: which package do people mostly use for local tests here?

Either way, it would be nice to get some more infos about further needed dependencies and maybe update the contribution guide part of the wiki.

Also, which minimum (or maybe maximum) node version does this project require to build correctly?

**Comment by tripu** [comment]
This should be better documented (and minimum requirements upgraded!) but right now: Node.js `8` or `10`.

https://github.com/gnab/remark/blob/develop/.travis.yml
