### ISSUE TITLE
Code highlighting like in the WordPress

### ISSUE THREAD

**Issue by 1alexvash** [gnab/remark#683]
Hey, just anybody knows it is possible to achieve a similar result:
![image](https://user-images.githubusercontent.com/46556479/189476122-a884d46f-d544-43aa-b8b3-f2c9645b0168.png)
It's a code snippet on my wordpress website

-----
When I try to use a Remark, I have the following for my markdown file:
![image](https://user-images.githubusercontent.com/46556479/189476199-b88db59e-3295-4832-92e7-66786c3b8fce.png)

![image](https://user-images.githubusercontent.com/46556479/189476184-712fe3d2-0e41-4d12-83c9-c1fb60473420.png)

Everything gets rendered properly except the code snippet, it just rendered there like a regular text

**Comment by tripu** [comment]
It's supposed to work: [presentation](https://remarkjs.com/#13), [docs in the wiki](https://github.com/gnab/remark/wiki/Configuration#highlighting).

Care to share your working example, eg in CodePen?

**Comment by 1alexvash** [comment]
I have found one live example how to use it properly:
https://codesandbox.io/s/0h5ii?file=/components/Layout.js

Now works as expected:
![image](https://user-images.githubusercontent.com/46556479/189535363-21383f2c-fdef-4d48-b2a0-f9a9ab699318.png)

**Comment by tripu** [comment]
@1alexvash:

I understand now: you are using [npm package `remark`](https://www.npmjs.com/package/remark), which is [this tool](https://remark.js.org/), which (in spite of the name) has nothing to do with [this project here](https://remarkjs.com/).

Go here instead: https://github.com/remarkjs/remark/issues
