### ISSUE TITLE
Auto-advance slides

### ISSUE THREAD

**Issue by gaul** [gnab/remark#689]
Is there any way to auto-advance slides, e.g., [PechaKucha](https://en.wikipedia.org/wiki/PechaKucha) 20-second format?  I imagine this could be done via the JavaScript console and some sleep loop?

**Comment by tripu** [comment]
Here you have an example:

https://codepen.io/tripu/pen/WNaJyLW

Does that answer your question?

**Comment by gaul** [comment]
Thanks @tripu!  I also found this carousel example in the wiki:

https://github.com/gnab/remark/wiki/Configuration#using-javascript-to-create-a-continuously-looping-slideshow

**Comment by gaul** [comment]
Huh, this double-advances when using the cloned window to show both the presentation and speaker notes.

**Comment by tripu** [comment]
An exercise left for the reader!

(I had no idea :)
