### ISSUE TITLE
remarkjs.com answers with 403

### ISSUE THREAD

**Issue by malkav30** [gnab/remark#699]
Hello,
I use remarkjs.com as a download link for the dependency. Today I noticed that my presentation does not work anymore, and the http://remarkjs.com/ domain seems unreachable :
- I get a 403 forbiddent on http://remarkjs.com/
- I get a SSL_ERROR_NO_CYPHER_OVERLAP on https://remarkjs.com

**Comment by tripu** [comment]
Works for me. Is that still happening to you?

**Comment by malkav30** [comment]
Yes. It happens on an entreprise network, let me check my outgoing proxy then.

**Comment by malkav30** [comment]
Indeed that's it, it seems that some Security Officer found out that it would be interesting to forbid access to this site :(
I close the issue, sorry for the disturbance.
