### ISSUE TITLE
Print a Presentation INCLUDING Speaker Notes

### ISSUE THREAD

**Issue by tbfe-de** [gnab/remark#70]
Are there any plans to support printing (= "export to File" from Chrome) with the speaker notes included?

What I'm thinking of is a portrait page format with the slide occupying ~1/3 of the page at the top followed by the notes for this page.

**Comment by Vebryn** [comment]
It's working fine on Chrome. Firefox and Opera don't seems to support notes printing.

**Comment by jknyght9** [comment]
Im having an issue printing slides with presenter notes in PDF. I have tried this with both Chrome and Safari and both do not display the slides or the notes correctly. In Chrome 59.0.3071.115 the slides are broken up and the notes print to the top, under the slide text. Safari does the same. Any suggestions?

**Comment by mathanimas** [comment]
I had the same problem, too. I found that, as a quick fix, it helps to add a custom style sheet to your presentation, containing a value for the top margin:

```
@media print {
 .remark-container.remark-presenter-mode .remark-slide-notes {
  margin-top:700px;
 }
}
```

This works for me in Safari. I imagine that the exact number of pixels (700 roughly works for me) may be different for various paper sizes. You may have to try different values.
