### ISSUE TITLE
Feature request: image scaling

### ISSUE THREAD

**Issue by khinsen** [gnab/remark#72]
Non-background images are always shown at their original size, which is often not at all adapted to a slideshow. For locally stored images, preprocessing is a solution, but not for pointing directly to images on other servers. Explicit image scaling would therefore be a nice feature to have.

**Comment by yijisoo** [comment]
I hope that the instruction on this useful feature should be added to the tutorial / wiki of the page.

**Comment by enrico16** [comment]
Naive question, but where should I place the macro definition?

**Comment by jochenvanwylick** [comment]
@enrico16 : right before this line

    var slideshow = remark.create();

**Comment by eduardohenriquearnold** [comment]
Great feature, makes Markdown cleaner and more compact. Maybe **macro definition** should be added to the Wiki page? It would make easier for new users to learn about this tool and use it.

**Comment by sffc** [comment]
Another little macro that keeps the alt text option:

```js
remark.macros.img = function (altText, width) {
  var url = this;
  return '<img alt="' + altText + '" src="' + url + '" style="width: ' + width + '" />';
};
```

Usage:

```
![:img my alt text, 50%](my-image.jpg)
```

**Comment by daaronr** [comment]
How could I get this to work with a locally stored image (not a url)?

In the slide 
``` 
.center[![trachoma](picsfigs/trachoma.jpg)]
```
Works well, but after adding the     
beforeInit: "macros.js"
and adding the macros to that file, knitting yields a blank presentation

**Comment by h-2** [comment]
This works great, can you add it to https://github.com/gnab/remark/wiki/Formatting#images so that people find it quickly?

One problem I have is that if you put images in Markdown tables, the column width is still scaled to full image size. Is there anyway around this?

Thanks!

**Comment by h-2** [comment]
> One problem I have is that if you put images in Markdown tables, the column width is still scaled to full image size. Is there anyway around this?

px instead of % seems to solve this:

```
![:scale 50px](image.jpg)
```
