### ISSUE TITLE
global markdown link definition

### ISSUE THREAD

**Issue by pinggit** [gnab/remark#75]
I'm trying to prepare my 1st remark.js presentations now...and what a wonderful html slides tool it is! thanks!

during my preparation I just found one thing: it looks for each slide the URL definition need to repeat , and can't span beyond current slides...

``` markdown
I like [remark][] , it's nice!
[remard]: http://remardjs.com

---

and I use [remark] to write my slides  <-- this doesn't work.
```

do I miss anything here? or it is just not supported (then  it's really a pity).

**Comment by gnab** [comment]
#246
