### ISSUE TITLE
how to insert embeded videos?

### ISSUE THREAD

**Issue by pinggit** [gnab/remark#94]
I've wondering how to insert the embeded video in remark  for days, I couldn't make it.
I'm totally new to remark and I don't quite understand HTML stuff..
but If I put following codes in my remark slides It was totoally just ignored...how to make it work?

```
<iframe width="560" height="315" src="//www.youtube.com/embed/82BGa-kkAAo?list=UUH9ciCUcWavMsFcAJtLUSyw" frameborder="0" allowfullscreen></iframe>
``
```

**Comment by obie** [comment]
This doesn't actually work. Any advice?

**Comment by kernc** [comment]
@obie Embedding YT videos kinda works. See [example](http://slides.coderdojo.si/p/predstavitev-hek.html#2)
